### ISSUE TITLE
Sidecar connects but does not show content

### ISSUE THREAD

**Issue by hstriepe** [ben-z/free-sidecar#10]
Please fill in the template below to speed up the review process:

**Mac model:**
Mac Pro 5,1 (mid 2012)
Radeon 7970
**iPad model:**
iPad Pro 10.5

**Mac version** (optional):
macOS 10.5.1
**iPad version** (optional):
iOS 13.3beta
**Comments:**
Systems connect fine. toolbar shows on iPad screen, but cannot drag Windows. No content shows.

**Comment by ben-z** [comment]
This is most likely because the older Mac can't keep up with the high res display that iPad Pro has. Try reducing the output quality of the sidecar display: https://github.com/ben-z/free-sidecar/issues/4#issuecomment-549176965

**Comment by ben-z** [comment]
Might be a dupe of #9. Can you try the workaround proposed there?
