### ISSUE TITLE
Will this patch take control of my files, etc.? How can I remove the patch if I didn't backup with time machine but I plan to wipe and restore my MacBook pro?

### ISSUE THREAD

**Issue by safirali** [ben-z/free-sidecar#101]
Please fill in the template below to speed up the review process:

**Mac model:** macbook pro 13 in (mid 2015)
**iPad model:** iPad pro 11 in 2018

**Mac version**:Catalina 10.15.4
**iPad version**: IPadOS 13.4.1

**Comments:**
 
How can I go about removing this patch if Im planning on wiping my MacBook clean and restoring/factory resetting to make it like new?

**Comment by ben-z** [comment]
Just restore the backup file, remove the boot flag and turn on SIP and your system should be in the state before applying the patch.

**Comment by ben-z** [comment]
Also any form of reinstallation will wipe away all changes made by this patch.
