### ISSUE TITLE
no Ipad8,1 in list

### ISSUE THREAD

**Issue by errthou** [ben-z/free-sidecar#103]
Mac model:MacBookPro11,1
iPad model:Ipad8,1 (iPad pro 11 Cellular)

Mac version: Catalina 10.15.4
iPad version:Ipad OS 13
 in free-sidecar on 4th step i just can't find my ipad model - list of ipads stops on 6.11. how to fix this

**Comment by wzh4464** [comment]
my iPad 7,3 is also not in the list

**Comment by errthou** [comment]
that's because you ipad, as my unit, supports sidecar right out of the box, so you have to enable support just for your mac only.

**Comment by omarlakkis** [comment]
Thanks, it wasn't clear that you have to enable for *both* ends, I chose "iPad 6,12" as that was the newest available on the menu.  

Do I have to go through all the steps again?

**Comment by errthou** [comment]
just enable your mac, if everything else you did pright, and that's it

**Comment by omarlakkis** [comment]
Worked. Thank you!

**Comment by ben-z** [comment]
Glad everyone figured it out! Perhaps I should add this to the documentation.
