### ISSUE TITLE
Warning about 10.15.5

### ISSUE THREAD

**Issue by jamiehaywood** [ben-z/free-sidecar#104]
Please could you warn users about doing this in 10.15.5

I followed the instructions to the letter and got an error when trying to set nvram boot args:
`nvram error setting variable - 'boot-args' (iokit/common) not permitted`

**Comment by ben-z** [comment]
You probably just didn't use sudo

**Comment by jamiehaywood** [comment]
To give some more context: I'm also on OpenCore, if that helps at all?

**Comment by ben-z** [comment]
I see that error when I run the nvram command without sudo. Did you try:

```
sudo nvram boot-args="amfi_get_out_of_my_way=0x1"
```

**Comment by tayhengee** [comment]
I ran into a problem when I updated to `macOS 10.15.5` from `macOS 10.15.4`, SideCar no longer works, I redo the steps accordingly, and OMG! My notification center and day time and all the system related icons are missing from the top bar! 

I reverted my SideCar file and it finally back to normal. It scares me! haha

Device: MBP 15 2019

**Comment by jamiehaywood** [comment]
yeah I did try with sudo..

**Comment by CMC-Daniel** [comment]
> I ran into a problem when I updated to `macOS 10.15.5` from `macOS 10.15.4`, SideCar no longer works, I redo the steps accordingly, and OMG! My notification center and day time and all the system related icons are missing from the top bar!
> 
> I reverted my SideCar file and it finally back to normal. It scares me! haha
> 
> Device: MBP 15 2019

Same issue, notification center and day/time are gone.
