### ISSUE TITLE
iPad Pro 1st gen. 12.9 not recognised as Sidecar device

### ISSUE THREAD

**Issue by zohozer** [ben-z/free-sidecar#105]
I do installed MacOS Catalina 15.5 yesterday on my MacBookPro retina mid. 2014 expressly to test the Sidecar feature with an iPad Pro 12.9" 1st gen. and to my surprise I realised that my MacBookPro it is not in the list of supported Macs for this feature.

Searching for a solution I discovered this project, I downloaded the latest "free-sidecar" binary file, and followed all the steps to the letter. I do activated the "MacBookPro11,3" option (green colour) and saved, signed the new file.

After reboot I do have an option to activate the Sidecar on my MacBook Pro but unfortunately I can't see my iPad Pro on the list of supported devices.

Please help to fix this issue.

<img width="669" alt="Screenshot 2020-06-14 at 11 37 15" src="https://user-images.githubusercontent.com/5983791/84591247-da2aec80-ae34-11ea-9d34-33998c02a633.png">

**Comment by zohozer** [comment]
> Gentle reminder:
> 
> * Did you go through all of the troubleshooting steps outlined in README.md?
> * Did you describe your devices (model+version) and what you've tried in the PR description?

Hi. Thank you for reply.
I do read a few times all the steps needed to be performed.
I do even edited the boot flags by running:

`sudo nvram boot-args="-v amfi_get_out_of_my_way=0x1"`

Hardware used: iPadPro Model Number: ML0N2CL/A (iPad6,7 : iPad Pro 12.9 inch, WiFi) and MacBookPro11,3

**Comment by zohozer** [comment]
I do tried all the points from the Readme.md (6. General questions to consider before opening an issue:).

The iPad it is recognised in Finder and it is connected using a wired connection.

**Comment by zohozer** [comment]
<img width="806" alt="Screenshot 2020-06-14 at 12 08 28" src="https://user-images.githubusercontent.com/5983791/84591644-0c8a1900-ae38-11ea-9cc6-dda15e20903e.png">

The iPad is recognised in Finder but not by Sidecar

**Comment by zohozer** [comment]
I do made more tests and I do managed to recognise the iPadPro by Sidecar but also seems that Sidecar want to connect only using Wifi connection and I do get a "The device timed out" error every time the MacBookPro it is trying to connect to iPadPro.

The wired connection it is not working.

<img width="689" alt="Screenshot 2020-06-14 at 12 31 31" src="https://user-images.githubusercontent.com/5983791/84592148-532d4280-ae3b-11ea-9283-32883379b8fb.png">

I do made all the things described here:
[https://softwaretested.com/mac/what-to-do-when-you-get-the-mac-sidecar-device-timed-out-error](https://softwaretested.com/mac/what-to-do-when-you-get-the-mac-sidecar-device-timed-out-error)
but without success.

**Comment by zohozer** [comment]
Finally working. The issue with "timed out connection" was solved by following the advice from this page:

[https://discussions.apple.com/thread/250717433](https://discussions.apple.com/thread/250717433)

**Comment by ben-z** [comment]
Glad you found the solution!

For future readers, the solution from that link is to log out of iCloud and log back in on both devices.
