### ISSUE TITLE
Not working on 10.15.5

### ISSUE THREAD

**Issue by goelrohit94** [ben-z/free-sidecar#106]
Please fill in the template below to speed up the review process:

**Mac model:** 2019 macbook pro
**iPad model:** ipad 6,11

**Mac version**: 10.15.5
**iPad version**: 13.1.2

**Comments:**
I followed the commands as written in the readme .. but sidecar is not working. 
I cannot see my ipad in System preferences -> sidecar
nor is Airplay getting enabled in System preference -> displays

**Comment by ben-z** [comment]
You'll need to provide more information (e.g. what troubleshooting steps you have tried) for anyone to help you.

**Comment by goelrohit94** [comment]
i tried 
https://github.com/ben-z/free-sidecar/issues/39#issuecomment-582487691

my ipad is showing up in finder and is trusted , but still wont show up under Sidecar
the ipad is on  13.1.2 if that makes a difference
Do i have to do any changes on the ipad itself ?
i have ipad 6,11 but when that didnt work i just tried with all the ipads enabled could that be a reason ?

**Comment by ben-z** [comment]
Enabling other models won’t have any negative effects. If you’ve exhausted all options in the README then there isn’t much that I can help with :(

**Comment by goelrohit94** [comment]
Hey ben , 
so i hadnt tried wireless mode yet and when i connected the macbook and ipad via bluetooth the ipad started to appear in sidecar and airplay menus.
but not i am getting "The device timed out" error when i try to connect sidecar.

Any suggestions on this ? Also any idea as to why its showing the ipad via bluetooth but isnt detected in wired mode ?

**Comment by goelrohit94** [comment]
figured it out : 
Keychain must be enabled in icloud on both devices.
This article was very helpful , please link it to readme if you find it helpful
https://appletoolbox.com/sidecar-not-working-in-ipados-and-macos-how-to-fix-sidecar-problems/#Seeing_unable_to_connect_errors

**Comment by ben-z** [comment]
Oh interesting. Thanks for sharing! Will add it to my notes for the next update
