### ISSUE TITLE
macOS 11

### ISSUE THREAD

**Issue by maciekish** [ben-z/free-sidecar#107]
**Mac version**: macOS 11 Beta

**Comments:**
Hi, `/System/Library/PrivateFrameworks/SidecarCore.frameworks/Versions/A/SidecarCore` doesn’t exist anymore and i can’t find it anywhere. New level of SIP from Apple? Even after `csrutil disable` it can’t be found.

**Comment by pookjw** [comment]
In my hypothesis, you should patch /System/Library/dyld/dyld_shared_cache_x86_64 (or dyld_shared_cache_x86_64h) but modifying this file is not highly recommended. So we need hook methods but it requires low-level knowledge of macOS.

**Comment by ben-z** [comment]
You guys are fast 🚄 😄

**Comment by sycomix** [comment]
./System/Library/PrivateFrameworks/SidecarCore.framework/SidecarCore

you're welcome :)

**Comment by JoeGodz** [comment]
Does it not exist or does it exist?
I'm also having the same problem

**Comment by sambancroft** [comment]
> ./System/Library/PrivateFrameworks/SidecarCore.framework/SidecarCore
> 
> you're welcome :)

I tried to use this file but get an error - have you tried amending this successfully?

**Comment by sycomix** [comment]
I was able to move past that error only to find several other errors. (factory reset macbook pro 15,1 big sur back to catalina) let me set a VM for big sur and I will see what i can find.

**Comment by tthoma24** [comment]
I believe this may be related to a change in Kernel and dynamic linker function in Big Sur. The release notes appear to be publicly available, so I don't think this is under NDA to discuss: https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes/#Kernel

According to that page, dynamic libraries are no longer provided on disk. I suspect this applies to PrivateFrameworks as well now, so to answer @JoeGodz's does it exist or not comment, the answer is "kind of" 🤪 I think the idea is to provide a sealed, precompiled, signed copy of the OS and system libraries that can't be modified so as to attest to the security and validity of the libraries. With that said, I'm in no way an expert on macOS or the underlying PrivateFrameworks, but I'm not sure one will be able to patch this since there's no place on disk that these libraries are accessible

**Comment by andreduong-zz** [comment]
So can you run this on macos big sur?

**Comment by ben-z** [comment]
Oops @andreduong just saw your comment. Nope. Let's keep this issue open for a while longer. I haven't had much time to look into this recently.

**Comment by gpnunes75** [comment]
We are about to Big Sur public final version. Do we have new considerations about it? Are we gonna have a new version of this procedure?

**Comment by arhoades1** [comment]
Does not work on late 2013 MBP MacOS 11 Beta 7
"no such file or directory"

**Comment by z98785z** [comment]
> I believe this may be related to a change in Kernel and dynamic linker function in Big Sur. The release notes appear to be publicly available, so I don't think this is under NDA to discuss: https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes/#Kernel
> 
> According to that page, dynamic libraries are no longer provided on disk. I suspect this applies to PrivateFrameworks as well now, so to answer @JoeGodz's does it exist or not comment, the answer is "kind of" 🤪 I think the idea is to provide a sealed, precompiled, signed copy of the OS and system libraries that can't be modified so as to attest to the security and validity of the libraries. With that said, I'm in no way an expert on macOS or the underlying PrivateFrameworks, but I'm not sure one will be able to patch this since there's no place on disk that these libraries are accessible

defaults write com.apple.finder AppleShowAllFiles -boolean true ; killall Finder

in terminal，this command can show some hidden files

**Comment by tthoma24** [comment]
> > I believe this may be related to a change in Kernel and dynamic linker function in Big Sur. The release notes appear to be publicly available, so I don't think this is under NDA to discuss: https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes/#Kernel
> > According to that page, dynamic libraries are no longer provided on disk. I suspect this applies to PrivateFrameworks as well now, so to answer @JoeGodz's does it exist or not comment, the answer is "kind of" 🤪 I think the idea is to provide a sealed, precompiled, signed copy of the OS and system libraries that can't be modified so as to attest to the security and validity of the libraries. With that said, I'm in no way an expert on macOS or the underlying PrivateFrameworks, but I'm not sure one will be able to patch this since there's no place on disk that these libraries are accessible
> 
> defaults write com.apple.finder AppleShowAllFiles -boolean true ; killall Finder
> 
> in terminal，this command can show some hidden files

The issue is these files aren't normally hidden from what I can tell, they are only available as a part of the prelinked kernel which is signed and sealed. I don't think it is going to be possible to patch this library in macOS 11.
