### ISSUE TITLE
Screen Recording Permissions don't work anymore

### ISSUE THREAD

**Issue by Wademk** [ben-z/free-sidecar#109]
My MacBook version is 11,1 and I'm on Catalina 15.5 so I followed the instructions and skipped step 9 (enabling SIP). Any apps that could previously record/share my screen don't work. Under Privacy and Security -> Screen Recording, I don't see any apps with a checkbox I just see a message "no apps have requested to record screen". I have tried screen sharing through Zoom and Chrome browser but the usual permission pop up doesn't come up, nor do I see the app in the Screen Recording system preferences. I'm going to revert to the backup and see if it fixes things.

**Comment by ben-z** [comment]
You are right, it's a new quirk that I also started seeing recently. Will note it in the readme in the next revision.

It is related to disabled SIP.

**Comment by jslegendre** [comment]
This is because of the AMFI boot-arg. SIP has nothing to do with TCC. If you choose to run with AMFI disabled you can use my tool `tccplus` to manually grant apps the permissions they need

https://github.com/jslegendre/tccplus

**Comment by ben-z** [comment]
Ooo @jslegendre that is really cool, thanks for sharing! I can't reproduce this anymore on my machine but if anyone else is experiencing this please try tccplus and tell us if it works for you 😄 .
