### ISSUE TITLE
My iPad is not listed on Step 4

### ISSUE THREAD

**Issue by suir1000** [ben-z/free-sidecar#11]
On Step 4 where it says "Click 'Enable' to enable sidecar for the device:", I see my MacBook's device identifier thing so I enabled that but I don't see my iPad's (I have the iPad Pro 10.5).

**Comment by ben-z** [comment]
iPad Pro is officially supported by Apple so it is not in the blacklist. There’s no need to enable it.

**Comment by suir1000** [comment]
Ah, okay. So I only needed to enable my 2015 MBP then. Got it, thanks!
