### ISSUE TITLE
Side car shows and I can select iPad. But no transfer of screen

### ISSUE THREAD

**Issue by kevinreid02** [ben-z/free-sidecar#111]
Please fill in the template below to speed up the review process:

**Mac model:** Mac mini 2012 6.1
**iPad model:** iPad Pro 12.9 series 1

**Mac version**:15.5.5
**iPad version**:13..5.1

**Comments:**everything went smoothly with no errors at anytime. I missed out step 9 and did the alternative. After a final reboot - my menu bar has been reduced to only a couple of items all the rest have disappeared. I checked sound and it is now unticked and I can’t tick the check box to restore it to the menu bar. There is no display in the menu bar, or time machine I can’t select the show time machine checkbox either.
More importantly - I can see Sidecar in system preferences and it opens to screen with three tick boxes which do still work, and a drop down which shows the iPad but when I select iPad the tick boxes grey out and it thinks it is using the iPad because that is ticked in the drop down. But there is no image on the iPad from the Mac mini. The mouse remains bounded to the original screen. Eventually the selected iPad untucks it self and the three tick boxes return to normal - this is after about 2-4 minutes

**Comment by kevinreid02** [comment]
Yes - in addition if I right click on my mouse while in finder - finder crashes and relaunches the same for safari some apps accept a right click as normal.

**Comment by KardanovIR** [comment]
Have the same issue!
