### ISSUE TITLE
The application “free-sidecar.app” can’t be opened.

### ISSUE THREAD

**Issue by coding-by-feng** [ben-z/free-sidecar#112]
Please fill in the template below to speed up the review process:

**Mac model:** Mac Pro 2018 16
**iPad model:** MPGW2CH（ipad 5th）

**Mac version**: 10.15.4
**iPad version**: 13.6

**Comments:** The application “free-sidecar.app” can’t be opened.

**Comment by ben-z** [comment]
It's probably blocked because the app is not signed by a paid developer account. Go to System Preferences - Security & Privacy - General and you should see a button that says "open anyway".
