### ISSUE TITLE
Nothing is being enabled

### ISSUE THREAD

**Issue by CaptialistKarlMarx** [ben-z/free-sidecar#113]
Please fill in the template below to speed up the review process:

**Mac model:**
MacBook Pro 11,1 (Macbook Pro 2013)
**iPad model:**
IPad 5,1 (IPad Mini 4)

**Mac version**:
Catalina 10.15.6
**iPad version**:
iOS 13.6

**Comments:**
Hi, whenever I click on the button it won't do anything, unfortunately. I looked at your guide and the button should be turning green and say it's enabled but it doesn't. I'm not the best at this sort of thing, help?
Here's a video
https://drive.google.com/file/d/1jfdX9rtFBgPBVkV7XVhTwgohs3NauriP/view?usp=sharing

**Comment by ben-z** [comment]
Make sure to copy the SidecarCore file out of the system folder. The app does not have sudo permissions.
