### ISSUE TITLE
iPad Pro Jagged Display

### ISSUE THREAD

**Issue by lincoln6842** [ben-z/free-sidecar#115]
Please fill in the template below to speed up the review process:

**Mac model:** Mac Pro 6,1
**iPad model:** iPad Pro 6,8 (iPad Pro 12.9inch 1st generation)

**Mac version**: 10.15.6 (19G73)
**iPad version**:  iPadOS 13.5.1

**Comments:**
![image](https://user-images.githubusercontent.com/32479175/88814264-72661080-d1ec-11ea-9a05-1985f6d17b25.png)
I'm not sure what I did wrong. I tried wired and wireless but it still remain the same condition.

**Comment by ben-z** [comment]
Whoa that's pretty bad. But AFAIK there's nothing we can do about this...
