### ISSUE TITLE
Can iPad OS 14 in iPad Air 2 use this Code？ the last-updated OS whether or not make the code loss efficacy? Can you help test it....

### ISSUE THREAD

**Issue by sid5785** [ben-z/free-sidecar#117]
Please fill in the template below to speed up the review process:

**Mac model:** Macbook Pro 2017
**iPad model:** iPad Air 2

**Mac version**:macOS Big Sur
**iPad version**: iPad OS4

**Comments:**

**Comment by ben-z** [comment]
I haven't tested the pre-release versions of iPadOS so I can't comment on this. For Big Sur there's a discussion here: https://github.com/ben-z/free-sidecar/issues/107
