### ISSUE TITLE
MacPro 5,1 Did not work! Safari, menubar items stopped working

### ISSUE THREAD

**Issue by ameyrupji** [ben-z/free-sidecar#119]
**Mac model:** MacPro 5,1 
**iPad model:** iPad Pro 2020

**Mac version**: 10.15.6 (19G73)
**iPad version**: 13.6

**Comments:** After following all the steps mentioned and having no issues with them. I noticed the following:
- Safari stopped working 
- Menu Items like time, Wifi, AirPlay symbol, Spotlight search etc. stopped showing up.
- Spotlight search stopped working 

Did a restore of the backup `SidecarCore.bak` for the system to fix the above mentioned issues!

**Comment by ameyrupji** [comment]
Yes and 
Yes

**Comment by StevenSeiden** [comment]
The same issues also exists on the MacBook Pro 11,1 in macOS 10.15.4.

**Comment by KhazanGu** [comment]
I reproduce that on my Mac with version 10.15.5 (19F101).
