### ISSUE TITLE
No option for MacBookPro 15' 2014

### ISSUE THREAD

**Issue by wizofe** [ben-z/free-sidecar#12]
Please fill in the template below to speed up the review process:

**Mac model:**
MacbookPro (Retina, 15-inch, Mid 2014)

**iPad model:**
iPad 6th generation / A1893

**Mac version** (optional):
Catalina 10.15

**iPad version** (optional):
iPadOS 13.2

**Comments:**
There's no option in the software to unlock it for the specific macbookpro model!

**Comment by ben-z** [comment]
Do you not see `MacBookPro11,2` and `MacBookPro11,3`?
<img width="696" alt="image" src="https://user-images.githubusercontent.com/5977478/68859077-7c72ce00-06b4-11ea-92d8-d33e0122d86a.png">

**Comment by ben-t-ayga** [comment]
ben-z, I don’t see a MacBookPro7,1 in that list. It’s a mid 2010 version I’m running. Will that get added at some point or is there a hardware limit on that machine?

**Comment by ben-z** [comment]
@ben-t-ayga MBP ‘10 doesn’t support Catalina thus won’t be in the list: https://support.apple.com/en-ca/HT210222

**Comment by wizofe** [comment]
Thanks, @ben-z. Indeed I do see it but I am silly, thought that was inches 🤦‍♂
