### ISSUE TITLE
free-sidecar requires disabling SIP in 10.15.4+

### ISSUE THREAD

**Issue by DrTParker** [ben-z/free-sidecar#125]
It seems that free-sidecar requires disabling SIP (and AMFI boot check) in MacOS 10.15.4+.

It is the conclusion (so far?) of issue 59, that AMFI boot check and more importantly SIP must remain off or the system doesn't work:  https://github.com/ben-z/free-sidecar/issues/59#issuecomment-603953953

This actually comes straight from the README as well.  Whether this can be fixed I do not know, but I felt it might best to track this directly.

**Comment by dzafman** [comment]
Sidecar works for me on 10.15.6 with a new MacBook Pro 16" to an iPad Pro 10.5".  I have an iMac (late 2014) which doesn't support sidecar, so that machine is functioning as expected.  It would be a bug, I think, if disabling SIP somehow made sidecar work for unsupported machines.

**Comment by 78rr7r67r67** [comment]
Bump since this is still an issue.
