### ISSUE TITLE
Disabling SIP(System Integrity Protection) leads to bad behaviour with other screen recording apps (Ex. Zoom)

### ISSUE THREAD

**Issue by PT2309** [ben-z/free-sidecar#130]
Please fill in the template below to speed up the review process:

**Mac model: MacBook Air (13-inch, Early 2015)** 
**iPad model: iPad Pro(10.5-inch)**

**Mac version**: macOS Catalina 10.15.7 (19H2)
**iPad version**: 14.0.1

**Comments:** 
I was successful in enabling the sidecar feature for my Early 2015 Mac Air with the compatible iPad Pro. This created an issue with other screen recording application. 

While joining a meeting through Zoom application, I wasn't able to share the screen. System Preference > Security & Privacy > Screen Recording didn't list zoom.us application. 

 ![System Preferences with sidecar enabled](https://user-images.githubusercontent.com/29910827/94436073-9c6e8b80-01b9-11eb-920a-6489d8a65489.png)

**Steps:**
Enabled the SIP in RecoveryOS mode using `csrutil enable` and restarted the system. This crashed my System Preferences with errors similar to [this](https://github.com/ben-z/free-sidecar/issues/59#issue-587305536) issue. 

**Worked**: Reverted the changes as mentioned in the documentation [here](https://github.com/ben-z/free-sidecar#free-sidecar) and I was able to share the screen with zoom.us as before.

![System Preferences after Revert](https://user-images.githubusercontent.com/29910827/94436321-efe0d980-01b9-11eb-90eb-a3ea8f1b740f.png)

**Comment by PT2309** [comment]
> Gentle reminder:
> 
> * Did you go through all of the troubleshooting steps outlined in README.md?
> * Did you describe your devices (model+version) and what you've tried in the PR description?

I have followed all the mentioned step.

**Comment by PT2309** [comment]
Found a similar issue closed because of the no-activity. 
[Issue](https://github.com/ben-z/free-sidecar/issues/109#issue-645770282) 

I haven't tried the tcc.framework workaround as it might lead to bad behaviour. 
@ben-z @anshulahuja98 If you could recommend workarounds or patch that is going to be released in future.

**Comment by tsui603** [comment]
same probloem

**Comment by rubycerebra** [comment]
This is still an issue, any solutions?

**Comment by anshulahuja98** [comment]
I faced the same issue when I upgraded to Big Sur, I had cleaned out the sidecar tool but I had not enabled SIP again. Hence my browser was not asking for permissions for camera and Mic.

The current solution for this is to go into recovery mode and do `csrutil enable`

If that breaks the sidecar, then you probably need to stop using this sidecar tool until it's able to support usage with SIP turned off properly

**Comment by anshulahuja98** [comment]
@ben-z  we should let this issue stay open for the time
People might come across this to fix their systems.

**Comment by anshulahuja98** [comment]
I can drop in a PR to add this to the troubleshooting guide in the README.
