### ISSUE TITLE
iPad Pro 12.9 v1 not listed, strange green bars

### ISSUE THREAD

**Issue by sciascia** [ben-z/free-sidecar#131]
Please fill in the template below to speed up the review process:

**Mac model:**
Mac Pro 6,1 (2013 Trashcan)

**iPad model:**
iPad6,7 (iPadPro 12.9 v1)
https://everymac.com/systems/apple/ipad/specs/apple-ipad-pro-1st-gen-wi-fi-only-specs.html

**Mac version**:
10.15.6

**iPad version**:
iPad OS 13.7

**Comments:**
Hi There, 

I see this when enabling Sidecar - see attached:
![ipad-pro](https://user-images.githubusercontent.com/875921/95143285-275f0f80-07d2-11eb-9268-f99e39d15f6d.png)

I've run through the troubleshooting, the iPad is wired, I restarted the Mac a couple of times, I'm using the latest versions of OSX, iOS and Are Sidecar. 

When I setup Free Sidecar, I couldn't find iPad6,7 in the list - should it be there? I downloaded the latest version.

Sorry if I've missed a step, any pointers would be much appreciated.

Cheers

Ben

**Comment by ichasecorals** [comment]
Hi @sciascia. I have the same iPad. Was this ever resolved?
