### ISSUE TITLE
iPad mini 5 Model not here?

### ISSUE THREAD

**Issue by MayorPlayz** [ben-z/free-sidecar#135]
Please fill in the template below to speed up the review process:

**Mac model:**MacBook Air 2017
**iPad model:**iPad mini 5

**Mac version**:MacBookAir7,2
**iPad version**:iPad11,1

**Comments:**No option for iPad11,1

**Comment by wsy** [comment]
iPad mini 5 is already allowed by Apple(by not including iPad11,1 in this disallow list).
This program only read and displays Apple's disallow list from SidecarCore and allows you to delete certain models from this list.
