### ISSUE TITLE
System crash then use revert step fail

### ISSUE THREAD

**Issue by answer603** [ben-z/free-sidecar#138]
Please fill in the template below to speed up the review process:

**Mac model: Macbook pro 2015 early
**iPad model: iPad Pro 10.5

**Mac version**: 10.15.7
**iPad version**: 14.2

**Comments:**
I forgot to use step 8 and causing crashing, then I try to do revert step from README section 8, after step5 and step6, I type that command it shows : no such file or directory.

**Comment by ashleyengel** [comment]
How did you fix this? this is exactly what is happening to me
