### ISSUE TITLE
Downloads/SidecarCore: No such file or directory

### ISSUE THREAD

**Issue by andlock34** [ben-z/free-sidecar#14]
Please fill in the template below to speed up the review process:

**Macbook Pro 10,1**
**iPad Pro 2018**

**Catalina 10.15.1**
**12.1.14 (16D57)**

**Comments: Step7 I get '..../Downloads/SidecarCore: No such file or directory' after I have typed in 'sudo cp ~/Downloads/SidecarCore /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore'**

Can you help?

**Comment by andlock34** [comment]
Sorry all, I realised I hadn't completed step 3, now I have the sidecar icon but it can't see 'any devices' have restarted ipad and macbook but no joy

**Comment by ben-z** [comment]
Did you try wired connection?

**Comment by andlock34** [comment]
Thanks for coming back to me. Yes its plugged in, itunes can see it and it charges etc but the airplay display can't see and the sidecar can't either.

**Comment by ben-z** [comment]
That's weird! Did you try restarting both devices and turning off wifi and bluetooth on the iPad?
