### ISSUE TITLE
Big Sur - Sidecar file missing from SidecarCore.framework

### ISSUE THREAD

**Issue by pozgo** [ben-z/free-sidecar#140]
**MBP 16" 2019:**
**iPad Air2**

**11.1 Big Sur**:
**iPadOS 14.4**:

`/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore`

The above file doesn't exist. I guess Big Sur changed the way the app is kept on the drive.

**Comment by borjaolivera** [comment]
MBP 13" Early 2015 - Big Sur 11.0.1
iPad Pro 12.9" - iPadOS 14.2

Same issue, can't find SidecarCore.bak anywhere.

**Comment by andker87** [comment]
Same on MacBook Air 13" 2017.
Path is ok until 
`/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/` but no `SidecarCore` folder.

Instead I have:
- `_CodeSignature` folder with `CodeResources` file in it
- `Resources` folder with [these](https://ibb.co/b1t8D7C) files in it
- `XPCServices` folder with `DisplayMarkup.xpc` file in it

**Comment by Vorob-Astronaut** [comment]
` ~% cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak
cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: No such file or directory`

**Comment by Noragami-1** [comment]
#####################
 % cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak
cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: No such file or directory
####################

I have the same issue.

**Comment by alexgfaria** [comment]
Same issue. MacBook Pro (Retina 13" 2015) on macOS Big Sur 11.0.1

**Comment by ruslan-ardashev** [comment]
Would love to get Sidecar up and running on Big Sur!

**Comment by vseferidis** [comment]
Same situation here. 

Waiting for an update.

**Comment by Antonet99** [comment]
Same issues on Big Sur 11.0.1, can't find the path.

**Comment by panza1370** [comment]
Bump :D

**Comment by brucexo** [comment]
Same issues on Big Sur 11.0.1,  still can't find the files yet

**Comment by gitsacha** [comment]
I have the same issue here after updating my 2012 map to Big Sur! Would love a solution

**Comment by gitsacha** [comment]
I have the same issue here after updating my 2012 mac to Big Sur... Would love a solution!

**Comment by tthoma24** [comment]
> > I believe this may be related to a change in Kernel and dynamic linker function in Big Sur. The release notes appear to be publicly available, so I don't think this is under NDA to discuss: https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes/#Kernel
> > According to that page, dynamic libraries are no longer provided on disk. I suspect this applies to PrivateFrameworks as well now, so to answer @JoeGodz's does it exist or not comment, the answer is "kind of" 🤪 I think the idea is to provide a sealed, precompiled, signed copy of the OS and system libraries that can't be modified so as to attest to the security and validity of the libraries. With that said, I'm in no way an expert on macOS or the underlying PrivateFrameworks, but I'm not sure one will be able to patch this since there's no place on disk that these libraries are accessible
> 
> defaults write com.apple.finder AppleShowAllFiles -boolean true ; killall Finder
> 
> in terminal，this command can show some hidden files

The issue is these files aren't "hidden" from what I can tell; they don't exist on the disk at all because they are only available as a part of the prelinked kernel which is signed and sealed. I don't think it is going to be possible to patch this library in macOS 11.

_Originally posted by @tthoma24 in https://github.com/ben-z/free-sidecar/issues/107#issuecomment-724323491_

**Comment by ruslan-ardashev** [comment]
Oh no. 

Hoping we find a way.

**Comment by pozgo** [comment]
I believe so. Somone with enough time on hand will figure it out. Xmas is coming so defo we will have a solution :D

**Comment by makalmyk** [comment]
Same here

**Comment by fabulousthee** [comment]
Same issues
M1 Mac mini Big Sur11.1
iPadAir2 iPadOS14.3

**Comment by anatoly314** [comment]
@fabulousthee , you have the newest Mac, it should work as is or I'm wrong?

**Comment by brucexo** [comment]
Are u sure?

发自我的iPhone

**Comment by tthoma24** [comment]
@fabulousthee @anatoly314 the reason it's not working for them is the iPad Air 2 is not supported since it lacks support for Apple Pencil.

**Comment by pozgo** [comment]
@tthoma24 - What are you talking about? So how it was working before BigSur then? I used my iPad Air 2 without any issues. We are missing the app bin which we can easily modify. That's all.

**Comment by jbeck22** [comment]
Same issues for me too
M1 MacBook Air Big Sur11.1
iPadAir2 iPadOS14.3

**Comment by varlenthegray** [comment]
Same here. 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/6404960/103454966-d5d1fe00-4cb6-11eb-8751-be86747183e2.png">

<details>
<summary>ls -lR results of said directory</summary>
ben@MacBook-Pro A % ls -lR
total 0
drwxr-xr-x  48 root  wheel  1536 Jan  1  2020 Resources
drwxr-xr-x   3 root  wheel    96 Jan  1  2020 XPCServices
drwxr-xr-x   3 root  wheel    96 Jan  1  2020 _CodeSignature

./Resources:
total 72
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 Dutch.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 English.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 French.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 German.lproj
-rw-r--r--  1 root  wheel  1412 Jan  1  2020 Info.plist
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 Italian.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 Japanese.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 Spanish.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 ar.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 ca.lproj
-rw-r--r--  1 root  wheel  4846 Jan  1  2020 com.apple.ipad-pro.pdf
-rw-r--r--  1 root  wheel  4461 Jan  1  2020 com.apple.ipad.pdf
-rw-r--r--  1 root  wheel  6738 Jan  1  2020 com.apple.iphone-x.pdf
-rw-r--r--  1 root  wheel  4444 Jan  1  2020 com.apple.iphone.pdf
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 cs.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 da.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 el.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 en_AU.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 en_GB.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 es_419.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 fi.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 fr_CA.lproj
-rw-r--r--  1 root  wheel   475 Jan  1  2020 framework.sb
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 he.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 hi.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 hr.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 hu.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 id.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 ko.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 ms.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 no.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 pl.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 pt.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 pt_PT.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 ro.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 ru.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 sk.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 sv.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 th.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 tr.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 uk.lproj
-rw-r--r--  1 root  wheel   518 Jan  1  2020 version.plist
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 vi.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 zh_CN.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 zh_HK.lproj
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 zh_TW.lproj

./Resources/Dutch.lproj:
total 8
-rw-r--r--  1 root  wheel  2816 Jan  1  2020 Localizable.strings

./Resources/English.lproj:
total 8
-rw-r--r--  1 root  wheel  3371 Jan  1  2020 Localizable.strings

./Resources/French.lproj:
total 8
-rw-r--r--  1 root  wheel  4561 Jan  1  2020 Localizable.strings

./Resources/German.lproj:
total 8
-rw-r--r--  1 root  wheel  4677 Jan  1  2020 Localizable.strings

./Resources/Italian.lproj:
total 8
-rw-r--r--  1 root  wheel  4767 Jan  1  2020 Localizable.strings

./Resources/Japanese.lproj:
total 8
-rw-r--r--  1 root  wheel  2916 Jan  1  2020 Localizable.strings

./Resources/Spanish.lproj:
total 8
-rw-r--r--  1 root  wheel  4414 Jan  1  2020 Localizable.strings

./Resources/ar.lproj:
total 8
-rw-r--r--  1 root  wheel  3588 Jan  1  2020 Localizable.strings

./Resources/ca.lproj:
total 8
-rw-r--r--  1 root  wheel  4487 Jan  1  2020 Localizable.strings

./Resources/cs.lproj:
total 8
-rw-r--r--  1 root  wheel  4236 Jan  1  2020 Localizable.strings

./Resources/da.lproj:
total 8
-rw-r--r--  1 root  wheel  4082 Jan  1  2020 Localizable.strings

./Resources/el.lproj:
total 8
-rw-r--r--  1 root  wheel  4730 Jan  1  2020 Localizable.strings

./Resources/en_AU.lproj:
total 8
-rw-r--r--  1 root  wheel  3371 Jan  1  2020 Localizable.strings

./Resources/en_GB.lproj:
total 8
-rw-r--r--  1 root  wheel  3371 Jan  1  2020 Localizable.strings

./Resources/es_419.lproj:
total 8
-rw-r--r--  1 root  wheel  4484 Jan  1  2020 Localizable.strings

./Resources/fi.lproj:
total 8
-rw-r--r--  1 root  wheel  3894 Jan  1  2020 Localizable.strings

./Resources/fr_CA.lproj:
total 8
-rw-r--r--  1 root  wheel  4641 Jan  1  2020 Localizable.strings

./Resources/he.lproj:
total 8
-rw-r--r--  1 root  wheel  3769 Jan  1  2020 Localizable.strings

./Resources/hi.lproj:
total 8
-rw-r--r--  1 root  wheel  4343 Jan  1  2020 Localizable.strings

./Resources/hr.lproj:
total 8
-rw-r--r--  1 root  wheel  3822 Jan  1  2020 Localizable.strings

./Resources/hu.lproj:
total 8
-rw-r--r--  1 root  wheel  4695 Jan  1  2020 Localizable.strings

./Resources/id.lproj:
total 8
-rw-r--r--  1 root  wheel  3216 Jan  1  2020 Localizable.strings

./Resources/ko.lproj:
total 8
-rw-r--r--  1 root  wheel  2842 Jan  1  2020 Localizable.strings

./Resources/ms.lproj:
total 8
-rw-r--r--  1 root  wheel  3176 Jan  1  2020 Localizable.strings

./Resources/no.lproj:
total 8
-rw-r--r--  1 root  wheel  3589 Jan  1  2020 Localizable.strings

./Resources/pl.lproj:
total 8
-rw-r--r--  1 root  wheel  4165 Jan  1  2020 Localizable.strings

./Resources/pt.lproj:
total 8
-rw-r--r--  1 root  wheel  4309 Jan  1  2020 Localizable.strings

./Resources/pt_PT.lproj:
total 8
-rw-r--r--  1 root  wheel  4299 Jan  1  2020 Localizable.strings

./Resources/ro.lproj:
total 8
-rw-r--r--  1 root  wheel  4554 Jan  1  2020 Localizable.strings

./Resources/ru.lproj:
total 8
-rw-r--r--  1 root  wheel  4645 Jan  1  2020 Localizable.strings

./Resources/sk.lproj:
total 8
-rw-r--r--  1 root  wheel  4133 Jan  1  2020 Localizable.strings

./Resources/sv.lproj:
total 8
-rw-r--r--  1 root  wheel  3978 Jan  1  2020 Localizable.strings

./Resources/th.lproj:
total 8
-rw-r--r--  1 root  wheel  4075 Jan  1  2020 Localizable.strings

./Resources/tr.lproj:
total 8
-rw-r--r--  1 root  wheel  4153 Jan  1  2020 Localizable.strings

./Resources/uk.lproj:
total 8
-rw-r--r--  1 root  wheel  4640 Jan  1  2020 Localizable.strings

./Resources/vi.lproj:
total 8
-rw-r--r--  1 root  wheel  4180 Jan  1  2020 Localizable.strings

./Resources/zh_CN.lproj:
total 8
-rw-r--r--  1 root  wheel  2074 Jan  1  2020 Localizable.strings

./Resources/zh_HK.lproj:
total 8
-rw-r--r--  1 root  wheel  2106 Jan  1  2020 Localizable.strings

./Resources/zh_TW.lproj:
total 8
-rw-r--r--  1 root  wheel  2174 Jan  1  2020 Localizable.strings

./XPCServices:
total 0
drwxr-xr-x  3 root  wheel  96 Jan  1  2020 DisplayMarkup.xpc

./XPCServices/DisplayMarkup.xpc:
total 0
drwxr-xr-x  6 root  wheel  192 Jan  1  2020 Contents

./XPCServices/DisplayMarkup.xpc/Contents:
total 16
-rw-r--r--  1 root  wheel  1827 Jan  1  2020 Info.plist
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 MacOS
drwxr-xr-x  3 root  wheel    96 Jan  1  2020 _CodeSignature
-rw-r--r--  1 root  wheel   508 Jan  1  2020 version.plist

./XPCServices/DisplayMarkup.xpc/Contents/MacOS:
total 440
-rwxr-xr-x  1 root  wheel  563104 Jan  1  2020 DisplayMarkup

./XPCServices/DisplayMarkup.xpc/Contents/_CodeSignature:
total 8
-rw-r--r--  1 root  wheel  747 Jan  1  2020 CodeResources

./_CodeSignature:
total 8
-rw-r--r--  1 root  wheel  747 Jan  1  2020 CodeResources
</details>

**Comment by barragansoftware** [comment]
I copied the file SidecarCore from another MacBook with Catalina version and it works until step 6, but i receive an error when I write "sudo mount -uw /". 
mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66

I read is a problem with Big Sur. Any idea?

**Comment by Feivel65** [comment]
don't have any solutions, just facing the same problems. Do you have any idea so far, @ben-z ? 
Not to stress though, I'd just really enjoy the secondary display :)

**Comment by Feivel65** [comment]
> @tthoma24 - What are you talking about? So how it was working before BigSur then? I used my iPad Air 2 without any issues. We are missing the app bin which we can easily modify. That's all.

absolutely wrong. iPad Air 2 is not supported for Sidecar by Apple and it could've only been working on Catalina using this Patch by @ben-z

**Comment by pozgo** [comment]
@Feivel65 absolutely not wrong mate. :D 

Let's clarify this a bit. 

1. We are discussing this on a repo that allows us to patch Sidecar to work on unsupported iPad's and iPhone's. 
2. When I/we say it was working before I think it's only logical to assume that it means after patching (see point 1), which now it's impossible on BigSur due to the issues discussed in this thread.

So I stand as before. `YES` iPad Air 2 was working on Catalina without issues. (in case you missed it ;) - `AFTER PATCHING`)

**Comment by crappysocks** [comment]
I don’t know the protocol but it seems as if free sidecar for Big Sur is a lost cause..

**Comment by alexgfaria** [comment]
I'm still hopeful

**Comment by soshimee** [comment]
:(

**Comment by alexgfaria** [comment]
☝🏻☝🏻☝🏻

**Comment by ben-z** [comment]
I think there're some discussions at https://github.com/ben-z/free-sidecar/issues/159 that may be of interest ^

**Comment by daodov** [comment]
i lost hope
