### ISSUE TITLE
Support for macOS Big Sur?

### ISSUE THREAD

**Issue by le0-VV** [ben-z/free-sidecar#143]
It looks like in macOS Big Sur Apple used a different way to make the SideCar plugin. And with the new SIP and disk-mirror-mounting mechanism that prevents patching, will free-sidecar be modified/remade to work on macOS Big Sur and beyond?

**Comment by nikhil-advait** [comment]
@ben-z Support for Big Sur would be awesome!
Hope you find some free time to make this work for the community.

Thanks.

**Comment by fourgates** [comment]
I would also love to see Big Sur support. I'm on a MBP Mid-2015.

**Comment by rkansal99** [comment]
The way sidecarcore is packed has been changed in BigSur, would not need a lot of work to add support. Keep up the great work

**Comment by silv3r23** [comment]
+1 the directory does not exist on 11.1

```
ls /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/
Resources	XPCServices	_CodeSignature
```

**Comment by pozgo** [comment]
Duplicate on #140

**Comment by eriknienhuis** [comment]
#159 It works!

**Comment by alexgfaria** [comment]
Can somebody PLEASE share the file? And instructions?
