### ISSUE TITLE
Nothing to patch in A folder. No sidecar core.

### ISSUE THREAD

**Issue by TheG3Project** [ben-z/free-sidecar#146]
Issue: No SidecarCore to patch? Nothing in A folder.
![Screen Shot 2020-12-14 at 10 36 47 PM](https://user-images.githubusercontent.com/73323444/102179943-e2ec9180-3e5c-11eb-96d5-8e022c4d8ab5.png)

Mac mini Late 2014
macOS Big Sur 11.0.1

**Comments:**
Super confused, nothing to patch

**Comment by cslaviero** [comment]
Same here. 

Macbook air 13 7,2 
macOS BigSur 11.0.1

**Comment by anatoly314** [comment]
Did somebody found the solution?

**Comment by TheG3Project** [comment]
No, it won’t work since Big Sur changed how sidecar works. Only works on Catalina. No patchers have Big Sur support.
