### ISSUE TITLE
BigSur verison

### ISSUE THREAD

**Issue by receand** [ben-z/free-sidecar#148]
is there any way to make it work on BigSur?
thank you!

**Comment by kolya009** [comment]
When trying to copy SideCore and make a backup, "cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak", terminal outputs " cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: No such file or directory".

I'm currently trying to run this on a 2020 i5 MacBook Air on MacOS 11.1 BigSur. I may have missed something... I'm not entirely quite sure... Any help would be really appreciated!

**Comment by kmk709** [comment]
Same here! I guess APPLE has changed the file path or type

**Comment by avaleriani** [comment]
same issue, not able to make it work on big sur

**Comment by Revel8804** [comment]
I can confirm this is not working on Big Sur. I have searched and searched through the system. Apple has made some change.

**Comment by Mr-zhaohy** [comment]
same issue

**Comment by HackYe** [comment]
same issue

**Comment by pozgo** [comment]
Duplicate of #140

**Comment by shhschilling** [comment]
Confirmed. Not working on big sur

**Comment by papucho** [comment]
Any updates?

**Comment by leozvc** [comment]
waiting for ....

**Comment by rtbittaker** [comment]
Same issue on Big Sur 11.2.3. Early 2015 Mac Book Pro

"cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak
cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: No such file or directory"

**Comment by sivagtr** [comment]
Didn’t try in my pc.
But, 

Has anyone tried to replace with this ? 
/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/XPCServices/DisplayMarkup.xpc
