### ISSUE TITLE
Catalina 10.15.7 issue?

### ISSUE THREAD

**Issue by reabo** [ben-z/free-sidecar#149]
Hi i have a macbook pro 2019 inch 15inch on Catalina 10.15.7 and a ipad air 2 with 14.3

I follow all the step in the guide and it seems to work! However it makes the rest of my mac not work. Apps crash and i cant see time etc in the top toolbar.

Im wondering if im following the guide wrong? Step 8 is confusing. i do everything from till step 7.

Then for step 8 I 

1. Put in this command `sudo codesign -f -s - /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore`
2. Then is command 
`sudo nvram boot-args="amfi_get_out_of_my_way=0x1"`

3. Reboot the mac and it should work perfect correct?

**Comment by reabo** [comment]
> Gentle reminder:
> 
> * Did you go through all of the troubleshooting steps outlined in README.md?
> * Did you describe your devices (model+version) and what you've tried in the PR description?

I did

**Comment by tomtidom** [comment]
I advise you to undo. Running your OS without csrutil enabled is not advised and meddles with privacy settings of apps. I was, for instance, no longer able to configure of use OBS.
