### ISSUE TITLE
After taking step5.  iMac 2015 mid is not boot up

### ISSUE THREAD

**Issue by hid925** [ben-z/free-sidecar#15]
Copy & paste step 1 to 4  on terminal

Reboot with cmd+R 

And taking step 5.

My iMac is not booting up. :(

**Comment by ben-z** [comment]
Oh interesting, step 5 is not supposed to be destructive. What troubleshooting steps have you tried?

**Comment by hid925** [comment]
Seems my iMac couldn't find the booting disk.   When I tried reboot,  it kept showing me question mark on the screen.  Somehow, I might have made a discrepancy on booting system.

Those are what i troubleshot

1. started with recovery mode -> checking the mounted drive ->  recover the OS   : didn't work

2. started with recovery mode(network) -> checking the mounted drive ->  recover the OS   : didn't work

3. Reset PRAM/NVRAM  

4. started with recovery mode -> checking the mounted drive ->  recover the OS   : didn't work

5. started with recovery mode -> unmount the all the drive -> setup the drive again ->  recover the OS   : finally worked.
