### ISSUE TITLE
Folders that refer to the sidecar on macOS Bigsur

### ISSUE THREAD

**Issue by Gabecar21** [ben-z/free-sidecar#154]
Hello Ben-z, I apologize first for my English, which is not very advanced.

I don't know if it's in your interest to develop a tool that works at Bigsur. I mapped all the folders and files that refer to Sidecar.

/ usr / libexec / SidecarDisplayagent

/ usr / libexec / SidecarRelay

/System/Library/PrivateFrameworks/SidecarCore.framework

/System/Library/PrivateFrameworks/SidecarUI.framework

/System/Library/xpc/launchd.plist

/System/Library/LaunchAgents/com.apple.sidecar-hid-relay.plist

/System/Library/LaunchAgents/com.apple.sidecar-relay

/ System / Library / PreferencePanes / Sidecar / Contents

I'm starting to study programming now and I still don't have the knowledge for a possible solution. So I decided to share my discovery.

Another detail I found during my research was something in the notes for macOS Bigsur talking about the system extensions being loaded directly from the kernel. This is probably the reason the SidecarCore file is not present in /System/Library/PrivateFrameworks/SidecarCore.framework.

It may be that after Bigsur it is impossible to have the sidecar on an old mac. But it may be that with this information a solution will be found.

**Comment by HackYe** [comment]
wait for solution
