### ISSUE TITLE
it doesnt exist `/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore`

### ISSUE THREAD

**Issue by ranon-rat** [ben-z/free-sidecar#157]
![a](https://media.discordapp.net/attachments/820472030474272769/832046894363443210/Captura_de_Pantalla_2021-04-14_a_las_19.16.51.png?width=1524&height=941)

**Comment by joaomlneto** [comment]
~Same for me. Running Big Sur 11.2.3 on a MBP 15" 2015.~

EDIT: That's probably the issue for me. Apple only supports MBPs from 2016 onwards. :)
