### ISSUE TITLE
把系统搞崩溃了

### ISSUE THREAD

**Issue by chengpengvb** [ben-z/free-sidecar#158]
按照上面的做法修改之后可以投屏，但是当我重启mac之后，访达打不开，其他的任何应用程序也打不开，唯一可用的就是终端，吓死我了，我的系统的10.15.7，ipad5，后来我在终端里面还原了之前备份的SidecarCore文件，重启之后恢复了，是不是我的系统版本高了

**Comment by duenboa** [comment]
you can just only do step 6, step7, then reboot.   **DO NOT execute step8 **
>> sudo mount -uw /
>> sudo cp ~/Downloads/SidecarCore /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore



maybe execute codesign cmd, will make side-effect to app verify .


when i execute chrome app,  is broken , error  like follow:  
-------------------------------------------
Reason: no suitable image found.  Did find:
  /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: code signature in (/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
  /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: stat() failed with errno=22
  /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: code signature in (/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?).

-------------------------------------------

**Comment by duenboa** [comment]
> 按照上面的做法修改之后可以投屏，但是当我重启mac之后，访达打不开，其他的任何应用程序也打不开，唯一可用的就是终端，吓死我了，我的系统的10.15.7，ipad5，后来我在终端里面还原了之前备份的SidecarCore文件，重启之后恢复了，是不是我的系统版本高了

我也遇到类似问题.  解法:  只执行第6,7步, 文件覆盖之后直接重启, 不要执行codesign.
