### ISSUE TITLE
Not working on Big Sur

### ISSUE THREAD

**Issue by samrth012** [ben-z/free-sidecar#159]
Please fill in the template below to speed up the review process:

MacBookPro 14
iPad mini 4

11.3.1
13

I have sidecar working on Mac but I want to enable it for the unsupported iPad mini 4th gen and also I don't have any directories mentioned in the app.

**Comment by samrth012** [comment]
Yes

**Comment by aungsatpo** [comment]
Unable to find /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore in Big Sur.

**Comment by samrth012** [comment]
Yes that's the thing

**Comment by RNZ01** [comment]
Any updates on this?
I have `/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore` too :(

**Comment by sduarteurbina** [comment]
Known issue with currently no solution.

**Comment by samrth012** [comment]
That's what we need the solution 🤦‍♂️, like my Mac is supported but the iPad isn't.

**Comment by RNZ01** [comment]
Fun fact is i tried this package on my older mac, And it broke the menu bar for the whole OS

**Comment by eriknienhuis** [comment]
### The Fix (Free-sidecar on Big Sur)

Today I saw this tool. I was interested because I've got an iPad air 2 laying around. It was sad to see that was not working on Big Sur. 

**But I have a fix!**
**Just copy the "SidecarCore.framework" folder from an older mac running Catalina.**
Then run the patch.

Good to know:
You can't mount the filesystem the old way, new way found here: https://itectec.com/askdifferent/macos-can-i-mount-the-root-system-filesystem-as-writable-in-big-sur/
I ran into some problems with apps crashing. Be 100% sure that you run the **code-sign** correct.

**Comment by eriknienhuis** [comment]
> ### The Fix (Free-sidecar on Big Sur)
> Today I saw this tool. I was interested because I've got an iPad air 2 laying around. It was sad to see that was not working on Big Sur.
> 
> **But I have a fix!**
> **Just copy the "SidecarCore.framework" folder from an older mac running Catalina.**
> Then run the patch.
> 
> Good to know:
> You can't mount the filesystem the old way, new way found here: https://itectec.com/askdifferent/macos-can-i-mount-the-root-system-filesystem-as-writable-in-big-sur/
> I ran into some problems with apps crashing. Be 100% sure that you run the **code-sign** correct.

I used the same model MacBook for the copy, I'm not sure if it works with all copies.

**Comment by aungsatpo** [comment]
> > ### The Fix (Free-sidecar on Big Sur)
> > Today I saw this tool. I was interested because I've got an iPad air 2 laying around. It was sad to see that was not working on Big Sur.
> > **But I have a fix!**
> > **Just copy the "SidecarCore.framework" folder from an older mac running Catalina.**
> > Then run the patch.
> > Good to know:
> > You can't mount the filesystem the old way, new way found here: https://itectec.com/askdifferent/macos-can-i-mount-the-root-system-filesystem-as-writable-in-big-sur/
> > I ran into some problems with apps crashing. Be 100% sure that you run the **code-sign** correct.
> 
> I used the same model MacBook for the copy, I'm not sure if it works with all copies.

Possible to share the folder?

**Comment by sduarteurbina** [comment]
> ### The Fix (Free-sidecar on Big Sur)
> Today I saw this tool. I was interested because I've got an iPad air 2 laying around. It was sad to see that was not working on Big Sur.
> 
> **But I have a fix!**
> **Just copy the "SidecarCore.framework" folder from an older mac running Catalina.**
> Then run the patch.
> 
> Good to know:
> You can't mount the filesystem the old way, new way found here: https://itectec.com/askdifferent/macos-can-i-mount-the-root-system-filesystem-as-writable-in-big-sur/
> I ran into some problems with apps crashing. Be 100% sure that you run the **code-sign** correct.

Nice find. I would try this but both of my Macs are on ARM (which only has Big Sur) and I don't know if you can mix and match system frameworks from x86 on M1 Macs (or if Rosetta can translate them at all).

I do have an external macOS 12 install so if anyone could share the framework, I could see if it works at all on M1 Macs.

**Comment by ben-z** [comment]
Whoa @eriknienhuis interesting! Can someone try this out and see if you can reproduce?

I’m a little occupied recently but I’m happy to discuss this and take PRs!

Cc @pookjw exciting news!

**Comment by samrth012** [comment]
So I gotta install catalina first and then copy the sidecars framework then open big sur and then use it 😂😂😂

**Comment by samrth012** [comment]
Do share the sidecore.framework file or folder, drive or mega link for Intel version.

**Comment by mtoohey31** [comment]
@eriknienhuis So I used the SidecarCore.framework folder from a Catalina 10.15.5 backup I had (I'm currently on Big Sur 11.4), and the Sidecar prefpane shows up, but as soon as I try to connect to my iPad I run into an error that I couldn't find documented anywhere else: "A miscellaneous error occurred (4097)". That's probably not super helpful but I figured I might as well note it down here, lmk if you've got any suggestions or ideas about ways to debug this in a more detailed way. I'd be happy to spend some time digging into this next week, but I'm not super familliar with macOS debugging.

**Comment by Antonet99** [comment]
Can anyone share the missing files? I'm on Big Sur too, so I don't have access to another Mac with Catalina, I can't copy the files. Thanks.

**Comment by alexgfaria** [comment]
can somebody PLEASE share the file?

**Comment by ben-z** [comment]
Pretty sure sharing the file is against Apple's TOS and will get taken down right away :P

**Comment by siinnan** [comment]
> ### The Fix (Free-sidecar on Big Sur)
> Today I saw this tool. I was interested because I've got an iPad air 2 laying around. It was sad to see that was not working on Big Sur.
> 
> **But I have a fix!**
> **Just copy the "SidecarCore.framework" folder from an older mac running Catalina.**
> Then run the patch.
> 
> Good to know:
> You can't mount the filesystem the old way, new way found here: https://itectec.com/askdifferent/macos-can-i-mount-the-root-system-filesystem-as-writable-in-big-sur/
> I ran into some problems with apps crashing. Be 100% sure that you run the **code-sign** correct.

hi I would like to know what I should do after getting the file from Catalina 
thank you!!

**Comment by eriknienhuis** [comment]
Hi guys, I'm sorry for the long respond. I'm currently not using the fix, I used an iPad from my work and I do not own an older iPad....  But: I can give you the missing files, it's the folder from a macbook air 2015. I've not tried it on an older or newer mac. 

Someone who can try it with an older or newer mac feel free to use my files. I hope this works.

[SidecarCore.framework.zip](https://github.com/ben-z/free-sidecar/files/6694517/SidecarCore.framework.zip)

**Comment by bertyterty** [comment]
> Hi guys, I'm sorry for the long respond. I'm currently not using the fix, I used an iPad from my work and I do not own an older iPad.... But: I can give you the missing files, it's the folder from a macbook air 2015. I've not tried it on an older or newer mac.
> 
> Someone who can try it with an older or newer mac feel free to use my files. I hope this works.
> 
> [SidecarCore.framework.zip](https://github.com/ben-z/free-sidecar/files/6694517/SidecarCore.framework.zip)

I tried it with your files. Annoyingly I didn't think about this when I finally updated to Big Sur so I didn't backup my old file, and it looks like I deleted my original backups after I tested it to be working, hence I downloaded your files.

Anyway, I went round the houses trying things in as many different ways I could. The best I got was that the computer would start and log on and was working relatively ok (a few issues with Terminal not having a history and crashing when I pressed up arrow), side car could see my iPad mini 4, but when trying to connect I get the same error as mthooey31, "A miscellaneous error occurred (4097)"

**Comment by soaringleefighting** [comment]
So now have a good solution for Big Sur ?

**Comment by pozgo** [comment]
I've fixed it by buying new iPad :D 

I know not real solution for old iPads but got tired of this and finally after 8 years of using old iPad decided its time for an upgrade.

**Comment by Le-Khuong** [comment]
any fix yet?

**Comment by rykelcruz** [comment]
still no fix?
