### ISSUE TITLE
iPad not showing up on Airplay after Installation 

### ISSUE THREAD

**Issue by SeanTheMan34** [ben-z/free-sidecar#160]
Please fill in the template below to speed up the review process:

**Mac model:** Mid 2012 Macbook Pro
**iPad model:** 8th Generation 10.2 inch iPad

**Mac version**:  10.15.7
**iPad version**: 14.4.2 

**Comments:**
I did every singe step on the installation, even did some of the troubleshooting steps- making sure the ipad is trusted and such, but yet it still will not pop up under airplay..?

**Comment by KrutavShah** [comment]
Same issue here with the same versions. I am using 2011 MBP and iPad 5th gen. It could be that the new IOS has additional implementations to prevent free sidecar.
