### ISSUE TITLE
Does this support iPadOS 14?

### ISSUE THREAD

**Issue by KrutavShah** [ben-z/free-sidecar#162]
Please fill in the template below to speed up the review process:

**Mac model: 8,2**
**iPad model: 6,11**

**Mac version**: 10.15.7
**iPad version**: 14.6

**Comments: I have a feeling that this patch does not work with iPadOS 14+, especially since the GitHub description lists iPadOS 13. I have setup everything correctly according to the README and followed the troubleshooting steps to no success. I do not have an iPad running iPadOS 13 since Apple does not allow downgrading.**

**Comment by ben-z** [comment]
Hi Krutav, I have not tested iPadOS 14 and it's possible Apple changed the blacklist process. I don't have a Mac running Catalina anymore so unfortunately I won't be able to test in the immediate future :(
