### ISSUE TITLE
SideCar for external touch screens?

### ISSUE THREAD

**Issue by YunaBraska** [ben-z/free-sidecar#163]
I wonder if it's possible to also activate sideCar for any external monitor.
It would be awesome to have these SideCar UI on other monitors

**Comment by ben-z** [comment]
Not with this project. This project only aims to unlock the functionalities on devices that already have the Sidecar feature (Apple simply disabled the feature).

**Comment by YunaBraska** [comment]
Yes I noticed that, but was just hoping to get some ideas how to.
