### ISSUE TITLE
Not working with big sur 11.6

### ISSUE THREAD

**Issue by moeak** [ben-z/free-sidecar#165]
Please fill in the template below to speed up the review process:

**Mac model:** early 2015

**iPad model:**

**OS version**: 11.6 Big Sur 
**iPad version**:

**Comments:**
cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak

It shows file not found for the new macos release 11.6 bigsur

{noformat}
Mohammads-MacBook-Pro:Resources Mohammad$ cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak
cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: No such file or directory
{noformat}

**Comment by PixelAgent007** [comment]
**Mac model**: MacBook Air 13" 2017 (Reports as MacBookAir7,2)
**OS version**: 11.6 Big Sur
**Comments**:

The file `/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore` doesn't exist anymore. The Folder `/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/` still exists, just the file doesn't.

**Comment by ananchev** [comment]
**Mac model:** MacBook Air 13'' M1 2020 
**OS version:** 11.6 Big Sur
**iPad model:** iPad Air 1st gen (ID iPad 4,2)

**OS version:** 11.6 Big Sur
**iPad OS version:** 12.5.5

Comments: `The file /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore` doesn't exist anymore. The Folder `/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/` still exists, just the file doesn't.

**Comment by moeak** [comment]
It seems no one is checking this?

Lets collaborate to fix this.

What should we be looking for? is there a keyword we should look for?

**Comment by oskardotglobal** [comment]
> It seems no one is checking this?
> 
> Lets collaborate to fix this.
> 
> What should we be looking for? is there a keyword we should look for?

I mean we need to find the SidecarCore Framework

**Comment by oskardotglobal** [comment]
But from what I understand & researched it is not possible because Apple changed the way how Sidecar works

**Comment by folofse** [comment]
/System/Library/dyld/dyld_shared_cache_xx could maybe be edited in the same way. It seams to contain the SideCarCore Framework.

**Comment by danielristic** [comment]
It's still happening for me, any workaround to get sidecar working on Big Sur?

**Comment by CurMeta** [comment]
Same issue: Folder /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore doesn't exist.

MacBook Pro 12,1 running with MacOS 12.1 (Monterey)
iPad mini (5th gen) running with iOS 15.2

**Comment by Pratham-commits-code** [comment]
Same issue with macos monterey m1 mba 12.1 and ipad 5th gen iOS 15

Need a different way to bye pass sidecar now

**Comment by Pratham-commits-code** [comment]
This issue was not fixed before github closed it

**Comment by gniewus** [comment]
Can we reopen this issue? How about Monterey?
