### ISSUE TITLE
macos Monterey and ipad mini4

### ISSUE THREAD

**Issue by TlyLen** [ben-z/free-sidecar#168]
Please fill in the template below to speed up the review process:

**Mac model:macbook pro m1 **
**iPad model:ipad mini4**

**Mac version:macbook pro**:
**iPad version:ipad mini4**:

**Comments:I want use sidecar with my ipadmini4(ios15.1) and macbook pro m1(macos12.0.1),could you help me**

**Comment by Pratham-commits-code** [comment]
Mac Model : Macbook Air M1 MacOS Monterey

iPad Model : iPad 5th gen 9.7 inch iPadOS 15
