### ISSUE TITLE
SidecarCore folder not present on unsupported mac with macOS Monterey

### ISSUE THREAD

**Issue by matt12f** [ben-z/free-sidecar#169]
Hi, I wanted to unlock sidecar on my MacBook Pro Retina (Early 2015) but when using your tool I quickly ran into an issue.

Basically `/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore` folder doesn't exist.

Maybe they stopped installing it on unsupported macs?
Any Idea how to get Sidecar installed? maybe get it from a more recent mac that has it installed?

Edit: it looks like Sidecar is build differently into the system after Catalina, even on a mac that supports it the folder is not present. So this workaround probably won't work on Monterey.

**Comment by clayesq** [comment]
Same issue here:

cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak
cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: No such file or directory

Looked manually as well. Going to download 12.1 pkg and poke around

**Comment by Teofilooliveira** [comment]
Mesmo aqui! alguém achou uma solução para o Big Sur?

**Comment by casamace** [comment]
Same thing here.The non-existence of the SideCarCore folder makes it impossible to proceed.

**Comment by casamace** [comment]
I forgot to mention that the problem is in my MacBook Pro 13" of 2015, running Monterey. The iPad should be no problem, as it is a 9th generation. Maybe inserting a fake SideCarCore file or folder in the right place would do the trick? But I have no idea of what this file/folder looks like!

**Comment by jaredbranum** [comment]
same issue. worth noting that `/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/` **is** present, but `SidecarCore` within that directory is not

**Comment by casamace** [comment]
Please, keep it open. I don’t understand that there is no answer from the developers, as it seems very easy to answer. Thank you.
Fernando del Pozo


On 4 March 2022 at 02:18:14, github-actions[bot] ***@***.***) wrote:

Closed #169.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by matt12f** [comment]
The project has likely been abandoned since Apple has changed the way in which sidecar is coded in the latest updates. So this workaround doesn’t work anymore, there’s likely no way to do something similar now. 
How is it “very easy” to answer?

**Comment by casamace** [comment]
Ok, I understand it cannot be done. But this could have been announced long ago. Thanks anyway.


On 4 March 2022 at 09:36:25, matt12f ***@***.***) wrote:

The project has likely been abandoned since Apple has changed the way in which sidecar is coded in the latest updates. So this workaround doesn’t work anymore, there’s likely no way to do something similar now.
How is it “very easy” to answer?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
