### ISSUE TITLE
iPad Pro 12.9" ipad6,8 removed from authorised devices

### ISSUE THREAD

**Issue by ormaa** [ben-z/free-sidecar#17]
MacBook Pro mid 2015
macOS 10.15.1
iPad 12.9 Wifi 3G (first gen of iPad Pro : iPad 6,8, ref A1652 on the back), with iOS 13.2.3, 

I followed the steps and got the SideCar working : 
my iPad 6 (2018) is recognised properly. it works pretty well.
 (few glitch on screen, but nothing very bad) 
my iPad Pro 12.9 " is not recognised.  This device is not black listed, so it should be in the recognised list.

I tried to reboot, to connect only the iPad Pro without success.

I believe that the patch remove the authorised device, and set only the blacklisted one ?

thanks for that apps.

**Comment by ben-z** [comment]
Nope this patch doesn’t affect devices that support sidecar. I recommend talking to Apple support for the iPad Pro issue

**Comment by ben-z** [comment]
If you wanna verify what I said, you can diff `SidecarCore` and `SidecarCore.bak` with a hex editor. You’ll see that only blacklisted devices are altered.

**Comment by ormaa** [comment]
Thank you for your quick feedback.

Finally, may be it could help some people, the iPad need to be connected to same iCloud account than the Mac.
And my iPad Pro was using my “pro” icloud account :o)

I will close my issue.
thanks

**Comment by ben-z** [comment]
Glad it’s resolved!
