### ISSUE TITLE
SidecarCore file doesn't exist on MacOS 12.0.1

### ISSUE THREAD

**Issue by ian41t** [ben-z/free-sidecar#171]
Please fill in the template below to speed up the review process:

Mac model: MacBook Pro 16-inch, 2019, 2.4 Ghz 8-core
iPad model: iPad 5th gen MP2H2LL/A

Mac version: 12.0.1 Monterey
iPad version: 15.2.1

Comments: I'm not able to complete Step 1 as the SidecarCore file doesn't exist. I have the folder, but no SidecarCore. Terminal error is:
cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: No such file or directory

**Comment by Rehan-shah** [comment]
hello, I am facing the same issue I check the README.md's troubleshooting but could not find it

**Comment by xube** [comment]
Sorry, but there is no support for OSX 11+ (Big Sur) so nor 12+ (Monterey)

No free-sidecar nor sidecar patcher. Just read readme thourougly. Only choice is Catalina as you can read in readme. You should send thanks and regards to Apple for screwing us again and again.

Your choices are Duet, Yam, Astropad, EasyCanvas... or just downgrade to Catalina.

**Comment by EmanuelFaria** [comment]
I got it to work on my 2012 Macbook Air running Catalina. Thanks!

Then I tried it on my 2019 Macbook Pro running Monterey, and now some of my apps crash at launch. How can I undo the damage I've done? (Sorry I have to bother you with this)

**Comment by llx1233** [comment]
Mac 12.0.1 has its own follow-up function and does not need to be opened separately

**Comment by Marion-China** [comment]
> Mac 12.0.1 has its own follow-up function and does not need to be opened separately
My iPad can't use  follow-up function, but my Mac is the other way around.I want use this features.How to I do when I use in MacOS 12.0.1?Thank you.
