### ISSUE TITLE
Really need this to work on macOS Monterey - please share some workaround :)

### ISSUE THREAD

**Issue by techtonic22** [ben-z/free-sidecar#173]
**Mac model: MacBook Air 2017**
**iPad model: iPad Air (2020)**

**Mac version:** MacOS Monterey

**Comments:**

Hi,

A lot of us are facing issues in configuring this on the latest macOS. Could the developers please help us out somehow making this work in Monterey? 

Would be highly grateful!

**Comment by tlamon** [comment]
YAM display did the trick for me :) https://www.youtube.com/watch?v=2299GO5MKgs
