### ISSUE TITLE
Cant Find the sidecar folder

### ISSUE THREAD

**Issue by Smiggle2406** [ben-z/free-sidecar#174]
Please fill in the template below to speed up the review process:

**Mac model:**
MBP 2019/2020
**iPad model:**
Ipad Air 2
**Mac version**:
Macos Monterny 12.4
**iPad version**:
Ipados 15.5
**Comments:**
i cant find the sidecar folder that i need to change

**Comment by VilterPD** [comment]
I have a similar problem: There is no SidecarCore file in the specified location (/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore)

I have gone through the Readme

**Comment by alihadiyan93** [comment]
Hi, my mac is running 12.3.1 (21E258) Monterey

in this case, I do not have such a file directory, as you can see as the attachment.

<img width="798" alt="Screenshot 2022-07-24 at 20 57 42" src="https://user-images.githubusercontent.com/28840125/180661907-c6967067-2877-4e88-8af2-f5601c94138c.png">

Kindly, Would you please support regarding this?


MacBook Pro (Retina, 13-inch, Early 2015)
2,7 GHz Dual-Core Intel Core i5

**Comment by jshmllr** [comment]
**Bump on this**

MacBook Pro (Retina, 15-inch, Mid 2015)
macOS Monterey 12.6.7

Same, when I goto in Finder, or run command in Terminal — 
In Terminal - 
`cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak`

Returns...
`cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: No such file or directory`
