### ISSUE TITLE
/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A does not have SidecarCore file

### ISSUE THREAD

**Issue by AlonSher1** [ben-z/free-sidecar#175]
Please fill in the template below to speed up the review process:

**Mac model:** macbook air 2020 m1
**iPad model:** iPad air 2

**Mac version**:monterey 12.5
**iPad version**:ipadOS15.6

**Comments:**

**Comment by hdfsyu** [comment]
im having the same problem...

**Comment by FTOCHER** [comment]
**Mac model**: Macbook Pro mid-2015 15'
**iPad model**: iPad (9th Gen)

**Mac version**: Monterey 12.5.1
**iPad version**: ipadOS15.6

Same issue here. No SidecareCore file can be found within 'A'.

**Comment by hdfsyu** [comment]
mines is early 2015

**Comment by xXcodgerXx** [comment]
I am experiencing the same problem. 

mac mini 8,1 (2018) Monterey 12.6
ipad 5th gen ipadOS 15.7

I'm not sure what steps to try since the readme contains steps for the hack not working but I am unable to even try out the hack.

**Comment by AleksIralda** [comment]
Same here,

Mac model: Macbook Pro mid-2015 15'
iPad model: iPad Pro 11 (2018)

Mac Versión Monterey 12.6
Ipad Version: ipadOS15.7

**Comment by xXcodgerXx** [comment]
> Same here,
> 
> Mac model: Macbook Pro mid-2015 15' iPad model: iPad Pro 11 (2018)
> 
> Mac Versión Monterey 12.6 Ipad Version: ipadOS15.7

Is it possible it only works on Catalina? I'm starting to think that is the case.

**Comment by ifuchs** [comment]
I'm also on 2015 MBP with Monterey and cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore gives "No such file or directory"
Anyone have a way to use this with Monterey?

**Comment by Adjutant-reflex** [comment]
I had the same issue. Looks like it's a known issue with FreeSideCar and covered a bit in the 'Pull Requests' tab. 

But in the work-around of that, the possibility of doing it wrong completely killing my computer might be a little too much risk for me.

**Comment by sonicdeviant** [comment]
Will need a new workaround for Monterey+ because SideCore is no longer located in that directory.

**Comment by yaoyi2008** [comment]
me too, macbook pro 2018 os version: 12.6.1, ipad mini4 os version: 15.5

**Comment by marieegl** [comment]
Same...
MacBook Pro 2021 | OS : 13.1
Ipad 5 | OS 16.2

**Comment by sebasop320** [comment]
Same.... 
MacBook Air 2017
iPad Pro 5th 12 inch display

**Comment by Danfrid** [comment]
https://www.reddit.com/r/MacOS/comments/pfxuee/how_can_i_install_lilukext_on_big_sur_1152/
https://github.com/acidanthera/FeatureUnlock

**Comment by PaulRyan17** [comment]
same issue here

**Comment by hdfsyu** [comment]
or this will be closed in 5 days

**Comment by nomm-dot** [comment]
Having the same issue. I have a m1 mac mini running monterey(supported) and an ipad mini 4 (unsupported). file does not exist in that directory. I found a shortcut to the file in a higher directory but the file does not seem to exist anywhere the shortcut directs to itself.

**Comment by timkondratev** [comment]
OpenCore Legacy Patcher seems to work:
https://www.youtube.com/watch?v=8Hctat7Cz9E
