### ISSUE TITLE
Working with mac os ventura 

### ISSUE THREAD

**Issue by amassias** [ben-z/free-sidecar#181]
Hi, has someone tried to do it using mac os ventura ? Is it working ?

**Comment by marooo326** [comment]
I tried to do it right before, but I failed at first step.
"cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak"

So I tried to find "SidecarCore" myself, but I couldn't find it. Maybe its structure has been changed..

**Comment by fg1998** [comment]
I don't think so. Cannot find sidecarcore file to be patched :(
OBS - macOS SONOMA
