### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by Cs59105** [ben-z/free-sidecar#184]
Please fill in the template below to speed up the review process:

**Mac model:**
**iPad model:**

**Mac version**:
**iPad version**:

**Comments:**

**Comment by tonyng3101** [comment]
Mac model: M1 Air
iPad model: Air 2

Comments: I didn't see the SidecarCore folder. There are only these folders in the `A` folder: `Resources, XPCServices, _CodeSignature`
