### ISSUE TITLE
No Devices in sidecar menu

### ISSUE THREAD

**Issue by misterruffian** [ben-z/free-sidecar#19]
Mid-2012 MacBook Pro 9,1
iPad Pro 10.5

10.15.1 MacOS
iPad OS 13.1.3

All steps followed, I've noticed people mentioning on the threads that their sidecar'd ipads showing a black screen, but mine isn't even showing any devices on the sidecar menu atall.

All steps taken, Ipad is trusted and showing on finder, restarted both ipad and mac, and even tried turning on and off the bluetooth and internet!

**Comment by ben-z** [comment]
Are the iPad and the Mac logged into the same iCloud account? https://github.com/ben-z/free-sidecar/issues/17#issuecomment-557078151

**Comment by misterruffian** [comment]
Yup, they're both logged into the same Apple ID
