### ISSUE TITLE
Error thrown by Step 8

### ISSUE THREAD

**Issue by bobwhosmiles** [ben-z/free-sidecar#2]
Mac model: MacBook Air (11-inch, Early 2015)
iPad model: iPad Air 2

Mac version: Catalina 10.15
iPad version: iPad OS 13.1.3

At Step 8 in the instructions I get the following:

```
/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: replacing existing signature
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore malformed object (unknown load command 8)
/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: the codesign_allocate helper tool cannot be found or used
```

Any ideas?

**Comment by ben-z** [comment]
Restore the original SidecarCore and do `xcode-select --install` to install the developer tools. Then copy the patched SidecarCore into the system folder again, then try codesigning.

Try not to leave unsigned SidecarCore in the system folder because it will crash applications that try to load that framework.

**Comment by bobwhosmiles** [comment]
Thanks Ben. Followed these steps, dev tools installed successfully, but still getting the same error when trying to sign the patched SidecarCore

**Comment by ben-z** [comment]
Interesting 😮. Try `xcode-select --reset`. (source: https://github.com/maciekish/iReSign/issues/95)

**Comment by bobwhosmiles** [comment]
Ran `sudo xcode-select --reset` then repeated the codesigning - still that same error. Baffled but thanks for trying to help :)

**Comment by ben-z** [comment]
Ah the second line might be indicating that the `SidecarCore` file wasn't properly modified!

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore malformed object (unknown load command 8)
```

Can you post your original and the modified `SidecarCore` binaries here for inspection?

(If you haven't, try to patch the original file again to see if the file is just accidentally corrupted)

**Comment by bobwhosmiles** [comment]
Tried all steps again from scratch but still getting an error:

```
Bob@Bobs-Air ~ % sudo codesign -f -s - /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: replacing existing signature
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore malformed object (unknown load command 8)
/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: the codesign_allocate helper tool cannot be found or used
```

I've attached the original and modified files as suggested. Thanks Ben
[Sidecar files.zip](https://github.com/ben-z/free-sidecar/files/3798664/Sidecar.files.zip)

**Comment by ben-z** [comment]
Weird. I was able to sign your binary on my system without any errors! After reading [this](https://stackoverflow.com/questions/9496100/mac-load-commands-corruption), I'm suspecting that your Xcode may be outdated. Try downloading/updating Xcode from the App Store and make sure it's `Version 11.1 (11A1027)` or newer.

**Comment by bobwhosmiles** [comment]
that solved it - thank you again

**Comment by ben-z** [comment]
Awesome!

**Comment by jafarvillan** [comment]
Hi I have bob’s issue - same error what he got in the big inning  now I can’t use my apps . Is there any way I can go back to the original
