### ISSUE TITLE
Does this work for 10.15.1?

### ISSUE THREAD

**Issue by mehdi9000** [ben-z/free-sidecar#20]
Just wanted to know if this is still valid.

**Comment by ben-z** [comment]
Yep!

**Comment by jcevo** [comment]
iPad mini 4 , macOS 10.15.1
 it is timeout when i connect the iPad. like that
![image](https://user-images.githubusercontent.com/4157773/70418560-98447680-1a9e-11ea-82f8-4d447d9b081f.png)

**Comment by ben-z** [comment]
Did you try everything in the [troubleshooting](https://github.com/ben-z/free-sidecar#troubleshooting) section? Specifically this

> 5. General questions to consider before opening an issue:
> Did you try wired mode?
> Does your device show up in Finder's sidebar?
> Did you click "trust" in Finder under the device tab?
> Did you try unlocking your iPad before connecting?
> Did you try restarting both devices and connecting again?

**Comment by ben-z** [comment]
@alvin87 Following up in #25
