### ISSUE TITLE
Will this work iPad 8,1, / 8,2 11in?

### ISSUE THREAD

**Issue by kweiganddmp** [ben-z/free-sidecar#21]
Please fill in the template below to speed up the review process:

**Mac model:** mid 2015
**iPad model:** iPad 8,1

**Mac version** (optional): 
**iPad version** (optional):

**Comments:** Does this work for the iPad 11 inch? 8,1 ?

**Comment by ben-z** [comment]
This supports any iPad that supports iPadOS

**Comment by sakhtar1979** [comment]
Apparently the UI does not give any option for iPad Pro. I tried just selecting the most recent iPad option but the results were not good on MBP 2015 with iPad Pro 11 inch model. The resolution was very low and flickering. Will it benefit from having correct iPad option in selection?

**Comment by ben-z** [comment]
This app is only used to enable Sidecar for unsupported devices. It simply removes unsupported devices from Apple’s blacklist. iPad Pro is officially supported so it’s not on the blacklist.

This app doesn’t change anything that would affect the quality of the display.

**Comment by ben-z** [comment]
Did you try usb connection?
