### ISSUE TITLE
Screwed my whole system how do I completely remove?

### ISSUE THREAD

**Issue by DeanWhitten** [ben-z/free-sidecar#22]
Please fill in the template below to speed up the review process:

**Mac model: MacBook Air 2017**
**iPad model: iPad 2017**

**Mac version** (optional):
**iPad version** (optional):

**Comments:**
Not sure what went wrong but lost the back up file and just want to remove the patch and all completely, but it crashes everything on my desktop when I try to do anything , browser crashes when I try to type and/copy /paste

**Comment by ben-z** [comment]
The problem probably occurred in step 8 when code signing SidecarCore. An invalid code signature will cause application crashes. If you lost the backup file, you'll need to properly execute step 8 to sign the patched file. Make sure Xcode is installed.
