### ISSUE TITLE
Enabled both mac and 4,1 ipad air but doesn't show up on list

### ISSUE THREAD

**Issue by limakalpaca** [ben-z/free-sidecar#23]
Hello,

I enabled both my MacBookAir7,2 and my 4,1 ipad air, however the ipad does not show up in the list of devices, regardless of being connected to wifi, bluetooth or directly plugged into the mac. I have ensured that the Ipad trusts the mac, both are on the same icloud account, any other ideas?

Thanks.

**Comment by shortbow123** [comment]
Is the iPad actually on iPadOS 13?

**Comment by limakalpaca** [comment]
Good thought, is there any way to push an iPad Air 4,1 to iOS 13? Looks like we are on the latest os12

**Comment by ben-z** [comment]
You’ll have to look elsewhere for getting a newer OS onto an older device. I’m not sure why iPad Air is on Apple’s blacklist when it doesn’t support iPadOS.

**Comment by limakalpaca** [comment]
Any thoughts on where to look for that?

**Comment by shortbow123** [comment]
Google would help, but since it isn’t supported through the OS it would be dang near impossible to get it running unless you somehow added the device firmware for your device to iPadOS

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
