### ISSUE TITLE
Connect by Type-CtoLighting timeout macOS 10.15.1  and iPad mini 4-iOS 13.2.3 

### ISSUE THREAD

**Issue by jcevo** [ben-z/free-sidecar#25]
Today i update my Mac to macOS 10.15.1 ,and reset the freeSideCar follow the guide , but i skip the step1 and step2 , use the old version SideCore. 
Now shows "timeout". But it can work well before update.
How can i fix it? Thanks.
![image](https://user-images.githubusercontent.com/4157773/70419108-c70f1c80-1a9f-11ea-9370-05771d4bd69f.png)

![image](https://user-images.githubusercontent.com/4157773/70418949-70a1de00-1a9f-11ea-865b-e555bb4f8f20.png)
![image](https://user-images.githubusercontent.com/4157773/70418954-73043800-1a9f-11ea-9ac6-bb8f921928cd.png)

**Comment by ben-z** [comment]
AFAIK SidecarCore changed in 10.15.1. Try using the new SidecarCore (I'm assuming you made a backup before overwriting it with the old one...)

If you didn't, you can probably find the binary in the 10.15.1 installation image. You can probably also find it on the internet.

**Comment by jcevo** [comment]
> AFAIK SidecarCore changed in 10.15.1. Try using the new SidecarCore (I'm assuming you made a backup before overwriting it with the old one...)
> 
> If you didn't, you can probably find the binary in the 10.15.1 installation image. You can probably also find it on the internet.

Yep ! I reinstall 10.15.1 and setup step by step . It's work well .Thanks
