### ISSUE TITLE
Set up OK but no connection

### ISSUE THREAD

**Issue by emhriv** [ben-z/free-sidecar#26]
Please fill in the template below to speed up the review process:

**Mac model:10,1
**iPad model: 2019 iPadPro 11"

**Mac version** 10.15.1 (Retina, Mid 2012)
**iPad version** (optional):

Used the tool to patch the SideCarCore with the 10,1 option. Had to update the Xcode tools to the latest. Everything went great, the Sidecar is visible in Sys Preferences. Also runs with no issue. 
MBPro -->USB A --> USB C --> iPad. 
Nothing is happening - no error, no issue but the Sidecar does not recognize the iPad. 
Tried all trouble shooting
Did you try wired mode?
Does your device show up in Finder's sidebar?
Did you click "trust" in Finder under the device tab?
Did you try unlocking your iPad before connecting?
Did you try restarting both devices and connecting again?

Nothing!!!

any ideas what else to try? Maybe lightning to USB C cable?

**Comment by ben-z** [comment]
Did you log into the same iCloud account on both the Mac and the iPad? https://github.com/ben-z/free-sidecar/issues/17#issuecomment-557078151

Also people have reported (but I can’t find it anymore) that they got it to work after signing out of, restarting and signing into the iPad.

Also you may be right about the cable. But it should work fine if you are able to see the device in Finder.

**Comment by emhriv** [comment]
Thanks for the quick reply!
Both devices are logged to the same iCloud account, however I’ll sign out and in again later today to see if this is going to solve it. 

I also have a couple of other new iPads that I didn’t have a chance to test. Will do later today. 

Ordered the lightning to usb C cable to test.

Will keep you posted on progress!

**Comment by emhriv** [comment]
Did some more testing. Patched the SideCarCore for MacBook Pro 10.1 and 10.2 as well as for iPad5.1. Here are the results

- iPad5,1; iPad mini4 2015. 
signed out my wife's account and signed in with my Apple ID. Works with cable, USB A to Lightning. Sidecar does recognize the iPad in wireless but give the 32002 error

 - iPad8,5/8,6; 12.9" iPadPro 3rd gen 2018. 
Brand new machine, signed in with my Apple ID. Works with cable, USB A to USB C. Sidecar does recognized the iPad in wireless but give the 32002 error

- iPad8,1/8,2; 11" iPadPro 2018. 
The initial machine that i tried. Did a factory reset on this one and then set it up as brand new machine. Signed in with my Apple ID. DID NOT work with cable, USB A to Lightning. Sidecar does not recognize the iPad in wireless

in both cases when the I made the connection the quality of picture on the both iPads were choppy... will check the quality once I get the Thunderbolt to USB C cable

**Comment by emhriv** [comment]
Did some more testing with different cable connections:

- HDMI (from MacBook Pro 2012) to USB C (iPad)
- Thunderbolt (from MacBook Pro 2012) to USB C (iPad)

None of the above works! The sidecar is ONLY supposed to work through USB (USB A to USB C or USB C to USB C)

I ultimately paid $10 USD for the Duet App and it works really well!

Thanks Ben-Z for coming up with workaround for older models...

Closing this issue!
