### ISSUE TITLE
No devices showing up

### ISSUE THREAD

**Issue by Natific** [ben-z/free-sidecar#27]
Please fill in the template below to speed up the review process:

MacBook Pro 9,2
iPad 6th gen

MacOS 10.15.2
iPadOS 13.3

Im signed into the same Apple ID on both devices and it shows no devices alvalible in the panel I have enabled every iPad model available but nothing I tried redoing the process but nothing
![Screen Shot 2019-12-11 at 12 36 07 PM](https://user-images.githubusercontent.com/49691910/70645331-d06cc600-1c12-11ea-9f82-b8f729796c62.png)

**Comment by ben-z** [comment]
Did you try wired?

**Comment by Natific** [comment]
I have only tried wired

**Comment by Natific** [comment]
I did try wireless but the iPad didn’t even show up in finder on wireless

**Comment by ben-z** [comment]
#26 is the same issue. Perhaps try things proposed in that thread?

**Comment by Natific** [comment]
Ok thanks I will check there and comment back if it works or not

**Comment by Natific** [comment]
Alright still nothing working tired Bluetooth, multiple cables and nothing

**Comment by Natific** [comment]
Ok I realized something just now I don’t have Xcode command line tools installed should I completely reinstall it with the tools or just install the tools and restart?

**Comment by Natific** [comment]
ok installed it and reinstalled the sidecar core still nothing I'm going to look more into this tomorrow if you can help me with this thanks

**Comment by ben-z** [comment]
Did you try https://github.com/ben-z/free-sidecar/issues/26#issuecomment-563871512?

**Comment by Natific** [comment]
yes

**Comment by Natific** [comment]
still nothing showing up

**Comment by ben-z** [comment]
I'm out of ideas :(. (This is out of the scope of free-sidecar. Try searching for general sidecar help)

**Comment by trebor513** [comment]
same problem here.
MacBook Air 2017: Catalina 10.15.2
iPad 6th Gen: iPadOS 13.3

Maybe because of 10.15.2 update???
