### ISSUE TITLE
Not working on macOS 10.15.2 

### ISSUE THREAD

**Issue by Valou447** [ben-z/free-sidecar#32]
**Mac model: MacBook Pro 13 inch, 2017 (without Touch Bar)**
**iPad model: iPad 5 Wifi (iPad 6,11)**

**Mac version** (optional): macOS Catalina 10.15.2
**iPad version** (optional): iPadOS 13.3

**Comments:**

On macOS Catalina 10.15.1, it used to work.
Since I resetted my MacBook on 10.15.2, it does not work anymore after following the same steps.

The device is shown up, but when selected it shows either 32002 or "Device was disconnected" error. 

I'm experiencing this with both wired and wireless mode..

**Comment by ben-z** [comment]
Did you make sure that the device is on wired mode by turning off WiFi and Bluetooth on the iPad?

The device shows up means that free-sidecar worked in removing the device from the blacklist. I’ll mark this as an apple issue.

**Comment by Valou447** [comment]
Yes I did, sadly still the same result..

**Comment by Valou447** [comment]
After trying out resetting trusted devices and re-pairing the iPad with the MacBook, I did manage to get it work in wired mode (still no wireless mode though)

I did follow steps in #7

**Comment by ben-z** [comment]
Since it works in wired mode and the behaviour of Sidecar is out of the scope of this project (free-sidecar only enables/disables sidecar), I'll close this issue :)
