### ISSUE TITLE
Antifeature removal

### ISSUE THREAD

**Issue by kbaegis** [ben-z/free-sidecar#35]
Please fill in the template below to speed up the review process:

**Mac model:**
Late 2016
**iPad model:**
12.9 inch iPad Pro

**Mac version** (optional):
**iPad version** (optional):

**Comments:**

I was wondering if any work had been done on removing Apple’s desperate ploy to get us all using iCloud/2fa. Is it possible to remove these requirements from the sidecar app as well? Anyone know how this is enforced?

**Comment by ben-z** [comment]
I'm not aware of any workarounds for that at the moment. It's probably more involved than editing a blacklist in the `SidecarCore` file.
