### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by Ibs2020** [ben-z/free-sidecar#36]
Please fill in the template below to speed up the review process:

**Mac model:** Mid 2015
**iPad model:** 6,4

**Comments:**
Sudo mount -uw / does not work for me, also the “ sudo cp ~/Downloads/SidecarCore /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore” doesn’t do anything.
What I’m getting is Read-only file system, so it can’t be overwritten. Anyone know a way around this?

**Comment by Ibs2020** [comment]
Mac model is Mid 2015
IPad model 6,4

What I’m getting is Read-only file system, so it can’t be overwritten. Anyone know a way around this?

**Comment by ben-z** [comment]
What error message do you get when running `sudo mount -uw /`?

Did you `disable csrutil` from the recovery partition before trying to mount?

**Comment by Ibs2020** [comment]
I have disable the csrutil.
the error I'm getting when I ran _sudo mount -uw /_ is..... mount: You must specify a filesystem type with -t.

**Comment by ben-z** [comment]
Do you have external drives connected? Try unplugging them

**Comment by ben-z** [comment]
Also have you googled this? What have you tried?
