### ISSUE TITLE
Catalina 10.15.3

### ISSUE THREAD

**Issue by Fealo** [ben-z/free-sidecar#38]
Hi, 
I just tried this with my 5th Gen Ipad and my MPB 2019 10.15.13, using a usb-c to usb 2.0. a and the classic lightening cable. it's not working. 
Am I doing anything wrong? What firmware do I need on my iPad?

**Comment by Fealo** [comment]
New to github, didnt realize there were closed issues.. Sorry

**Comment by ben-z** [comment]
Could you comment here which closed issue solved your problem?

**Comment by Fealo** [comment]
I had the wrong version activated (iPad 5th gen = iPad 6,11/6,12). 
Also I had to sign out of and into iCloud again to make it work. Working perfectly on wired, 
MacbookPro 13 inch 2019 10.15.3 and iPad 5th Gen 13.3.1 now!
Thank you for making this work. So far, wireless does not work, I case that's also possible I'd be happy about a hint. Otherwise: thanks!

**Comment by ben-z** [comment]
Thanks for the info!

I'm currently not aware of a way to make wireless work if it doesn't work out of the box :(.
