### ISSUE TITLE
Error Code 32002

### ISSUE THREAD

**Issue by kolakidd** [ben-z/free-sidecar#39]
I'm getting the error code 32002 issue. iPad Air 2 Wired and MacBook Pro 2017. 

Anyone have any quick fixes? I've been trawling Google, and it's the usual complaints, half truths, and mystery meat.

**Comment by ben-z** [comment]
Check if the device is unlocked and trusted in Finder

**Comment by kolakidd** [comment]
Hi thanks, yes all done. Also tried:
Mirroring display first
Reset trust settings on iPad
Firewall disabled on Mac

I haven't reset my MacOS networking or deleted my pref folder. This are kind of my last resort.

BTW. Thanks for the effort behind this workaround Ben, when it was working it was awesome!

**Comment by ben-z** [comment]
OP from #38 found luck signing out/in iCloud. Perhaps try that if you haven't already: https://github.com/ben-z/free-sidecar/issues/38#issuecomment-582395472

**Comment by kolakidd** [comment]
Thanks, I deleted my preferences MacHD>Library>Preferences>SystemConfiguration>preferences.plist
and it worked. Funny, back in the day (OS 9) that was the go to solve for any issue, just shows how far we have come that I was hesitant to do it.

Sorry about the verbose file name, but may be useful for someone else. I read something about persistent iPad settings in preferences that led me down that route. 

So for future reference, these are the things I saw documented:

- Reset trust settings on iPad
- Try mirroring display first
- Disable Mac Firewall
- Log out and back into iCloud on both devices
- Delete preferences.plist

**Comment by ben-z** [comment]
Thanks for sharing your experience! I'll add this to README as a general troubleshooting step.

**Comment by monstermunchguy** [comment]
hi guys,
went through the entire troubleshooting including the additional found here above and absolutely nothing worked for me.
The issue for me was actually my VPN on my MBA 2017. As soon as I disconnected it the iPad mounted as a 2nd screen.
I did not need to disconnect my VPN on my iPad.
MBA 2017 original apple cable to iPad Pro 12.9 first gen.
Hope this can help others...?

**Comment by ben-z** [comment]
Thanks for sharing your experience @monstermunchguy. Since you are using wired, I don't see how VPN can affect the connection 😮. I'm suspecting your Mac is still connecting to your iPad through wireless.

Also which VPN software are you using on your Mac? Might be useful to know that it affects Sidecar.

**Comment by monstermunchguy** [comment]
I'm using express VPN on all my devices.
I've just tried connecting MBA and iPad with and without wifi it always connects fine.
If I turn on my VPN while connected to the iPad I see the following message on the iPad's screen = Connecting / Switching to wireless / Disconnect
If I try to connect to the iPad while the VPN is already connected I get the error 32002

**Comment by ben-z** [comment]
Good to know. Thanks for sharing!

**Comment by dickinson-lab** [comment]
Just a note to say that the VPN trick worked for me too.  When connected through Cisco Anyconnect on my Mac, I was unable to mount the iPad as a second display even though I was using a wire (wireless and bluetooth were disabled on the iPad to force it to use the wired connection).  As soon as I killed the VPN connection, Sidecar worked flawlessly.  
Using Mac OS 10.15.6 and iOS 13.6.1.
