### ISSUE TITLE
MacBook Pro 15" Mid-2014 and 10.5" iPad Pro Graininess

### ISSUE THREAD

**Issue by ruthloose88** [ben-z/free-sidecar#40]
Just discovered this handy app and got SideCar enabled on my 2014 MBP, but the picture quality is very grainy with a wired connection. Just wondering if there is a terminal command I can use to improve the video quality.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19435610/73785732-dd66eb00-4765-11ea-93ab-98afc17002cc.gif)

**Comment by ben-z** [comment]
This is a common issue for newer iPads connected to older Macs. It happens because there is no hardware acceleration for HEVC. See past issues such as #4 for discussions.

**Comment by ruthloose88** [comment]
Thanks, @ben-z. 

I tried your solution to #4 using a resolution solution like Display Monitor and Easy Res. Both provided no additional resolution options to select from, so I wonder if it is a GPU issue and the fact that that MacBook Pro has an Intel Iris Pro 1536 MB VRAM (built-in). 

This may not be an issue for MBPs with a discrete GPU. and probably why my MBP was on Apple's blacklist in the first place .

**Comment by ben-z** [comment]
Ya the discussion in #4 didn't arrive at a solid conclusion...

The 15 inch MBP 2015 is on the blacklist as well though, so I'm suspecting it might not entirely be a GPU issue.

[The T2 chip in newer Macs provide hardware HEVC acceleration](https://www.apple.com/newsroom/2018/10/new-mac-mini-packs-huge-punch/). I'm suspecting that in Sidecar, there's a snippet that looks like:

```
if (MBP 2016 or MBP 2017) { # doesn't have T2 Chip
   use a special encoding
}
```

where the special encoding is one that is suitable for running on GPUs.

I'm wondering if we trick sidecar to recognize an MBP 2015 or older as a 2016/2017 MBP, it would provide a better quality.

**Comment by ruthloose88** [comment]
@ben-z , if you need a guinea pig, I'd be willing to edit the file to exclude that line of coding. Of course, part of me is wondering how much this might tax my laptop.

**Comment by ben-z** [comment]
We'll first have to figure out where that is in the SidecarCore binary 😄. If you are comfortable fiddling with it, please feel free to! A good tool is [iHex Editor](https://github.com/ben-z/free-sidecar/issues/39#issuecomment-582487691). I would start by looking up the device identifiers for MBP 2016 and MBP 2017 in SidecarCore and see if changing them has any effects.

Remember to always keep a backup!

**Comment by ruthloose88** [comment]
@ben-z  I may run the SidecarCore binary on my 2014 MBP and my 2018 MacBook Air (work computer) just to see how and if these differ (given that one is whitelisted and one is blacklisted). I'll give it a look later and see if it makes sense to dump the hex editor results or not here.

**Comment by ruthloose88** [comment]
I'm not finding anything that references the T2 Chip, HEVC or H.265 encoding. 

I did find a number of device configurations under the header "SidecarDisplayConfig" like "keyFrameInterval," "rtcp TimeoutInterval," "setLowLatency" and "setScale."

Nothing pops out at me that seems like the answer yet.

I am attaching a couple of finds from my 2018 MacBook Air Sidecar Core binary (started there to see if it referenced T2 or HEVC). I will look again later.

[2018 MBA SideCar Core.txt](https://github.com/ben-z/free-sidecar/files/4162109/2018.MBA.SideCar.Core.txt)
