### ISSUE TITLE
Frequent error, wireless mode, and touch screen

### ISSUE THREAD

**Issue by ciring** [ben-z/free-sidecar#42]
Please fill in the template below to speed up the review process:

Mac model:MacBookPro13,1
iPad model:5,3

I really appreciate your code. It works after the last step. However, 32002 mistake often appears，sometimes shows The device is disconnected, and I can't connect to iPad at all in wireless mode, my touch screen doesn't work even in sidecar mode

**Comment by ben-z** [comment]
That’s a common issue. Just reconnect multiple times and it should work. (Or make sure the iPad is connected and unlocked before starting sidecar.) Sidecar does not support touch screen, only Apple Pencil.
