### ISSUE TITLE
Add iPhones

### ISSUE THREAD

**Issue by ann0see** [ben-z/free-sidecar#43]
According to this repo [Sidecar-for-iPhone](https://github.com/BreckenLusk/Sidecar-for-iPhone/blob/master/README.md) it is possible to enable sidecar on jailbroken iPhones. However your app does only include iPads. Would it also be possible to add iPhones in general?

**Comment by ben-z** [comment]
`SidecarCore` doesn't contain iPhone models in the blacklist. If you've made the corresponding changes on the iPhone (see [1] below) and the instructions do what the doc claims, then you shouldn't need any further actions to see the iPhone in the list.

[1]: Taken from https://github.com/BreckenLusk/Sidecar-for-iPhone/blob/master/README.md

> 1. Install Filza File Manager
> 
> 2. Install NewTerm 2
> 
> 3. Navigate to /Applications/Sidecar.app in Filza
> 
> 4. Find the Info.plist file & tap on it
> 
> 5. Click the ⓘ next to SBIconVisibilityDefaultVisable
> 
> 6. Flip the switch on, which should change the value from NO to YES
> 
> 7. Tap "< Info.plist" in the upper left corner.

**Comment by pookjw** [comment]
That method only enables showing Sidecar app on SpringBoard, it doesn't enable Sidecar deamon on iPhone.

**Comment by ann0see** [comment]
So how can it be started?
Sidecar-relay does seem to run on my Phone

**Comment by ann0see** [comment]
Any news?
