### ISSUE TITLE
Mac OS is going to be installed after Step 8

### ISSUE THREAD

**Issue by ElForastero** [ben-z/free-sidecar#44]
After Step 8 (signing) and rebooting into recovery to disable Integrity Protection, I get MacOS installation process. 🤷‍♂️

![IMG_20200210_103617](https://user-images.githubusercontent.com/5102818/74126468-6f9d4200-4bf1-11ea-8477-df7e955df730.jpg)

### UPD:

![image](https://user-images.githubusercontent.com/5102818/74127202-63b27f80-4bf3-11ea-8625-9f02a99da7eb.png)

Maybe this is happening because I used some tricks to enable SideCar before. It was a long time ago, after Catalina release 🤔

**Comment by ben-z** [comment]
LOL the installer runs after you modify SidecarCore? Can you verify the SidecarCore file is patched by opening it in free-sidecar (open /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore in free-sidecar)?

**Comment by ElForastero** [comment]
@ben-z Nope, it wasn't patched.
And it was modified at 23 January... Either it was restored during this installation process, or I have missed something during patching process. But I'm pretty sure I went though all steps. 🤔


![image](https://user-images.githubusercontent.com/5102818/74244433-d6f2e900-4cfa-11ea-8ce1-a9f23ce2fa35.png)

**Comment by ben-z** [comment]
Hmm redo all the steps and see if it goes into the installation process again? It could be that you just had an update pending restart

**Comment by ElForastero** [comment]
Yeah, it works now! Probably I indeed had a pending update.

But, anyway, the quality is amazing via both wired and wireless connections. 😁 I would better use some third-party apps for screen sharing, like Yam Display.

![image](https://user-images.githubusercontent.com/5102818/74324817-0c521200-4da1-11ea-8b32-c567663108f9.png)
