### ISSUE TITLE
AMD Hackintosh, connect with USB success but ipad only shows a blackscreen with sidebar

### ISSUE THREAD

**Issue by ProphetRush** [ben-z/free-sidecar#45]
Please fill in the template below to speed up the review process:

**Mac model:** hackintosh with 3700X and opencore
**iPad model:** ipad 6,11

**Mac version** (optional): 10.15.3
**iPad version** (optional): 10.15.4 beta3

**Comments:**
My specs is 3700X AMD Hackintosh with opencore 0.5.5 and a RX580 installed, I successfully managed to connect the sidecar with my ipad 5th gen, but the ipad only shows a blackscreen with sidebar, where did I do wrong?

**Comment by ProphetRush** [comment]
Reason found, issue closed. https://github.com/AMD-OSX/AMD_Vanilla/issues/48

**Comment by IOIIIO** [comment]
Could you explain your fix?

**Comment by ProphetRush** [comment]
There is no fix for AMD Hackintosh
