### ISSUE TITLE
can't find my Ipad

### ISSUE THREAD

**Issue by echang95595** [ben-z/free-sidecar#46]
Please fill in the template below to speed up the review process:

**Mac model:** Macpro 2014 Catalina
**iPad model:** Ipadpro 10.5inch 

**Mac version** (optional): Catalina 10.5.3
**iPad version** (optional): IOS 13.3.1

**Comments:**

Hello when I click enable sidecar I see a bunch of Ipads and Macpros but not my Ipad 
I tried logging out from iCloud on both devices, connected them with a USB cable, made sure they're trusted and even deleted the preference list but still can't find it on the list. 
Could you help out?

**Comment by ben-z** [comment]
Do you mean you can't see you iPad model in the free-sidecar app? Your iPad natively supports sidecar so there's no need to enable it with the app. Just enable your Mac.

**Comment by yungfalcon562** [comment]
I have the same issue. iPad Pro 9.7 ipad6,3 and it doesn't not show up on device list. The device list is grayed-out without an option to select a device. Any ideas about that happening? I hope I didn't miss this question somewhere else..

**Comment by ben-z** [comment]
If your Mac is officially supported or you've used free-sidecar to enable it, then your iPad should show up in the devices list. What [troubleshooting](https://github.com/ben-z/free-sidecar#troubleshooting) steps have you tried?

**Comment by yungfalcon562** [comment]
Thank you for your feedback. I am new to GitHub and I realized that someone else logged out of their iCloud account on both their devices (laptop and iPad) and proceeded to restart the devices. Then, I logged back into iCloud on both my devices, waited for the iPad to sync on the laptop, and finally it was found by sidecar.

**Comment by ben-z** [comment]
Awesome! Glad to hear that it’s working
