### ISSUE TITLE
"A miscellaneous error occured (32002)" keeps coming up

### ISSUE THREAD

**Issue by mithem** [ben-z/free-sidecar#47]
Please fill in the template below to speed up the review process:

**Mac model:** MacBookPro 15,2
**iPad model:** 6,11

**Mac version** (optional): 10.15.3
**iPad version** (optional): 13.3.1

**Comments:**
(both in wired and wireless mode.) Everytime I try connecting to my iPad via settings > Sidecar or AirPlay in the status bar, sidecar does start on my iPad but on the MacBook, the error message states error 32002.
Sidecar stays opened on the iPad, when I try again, it pretty immediately closes while macOS says "the device was disconnected", sidecar on iPad closes. Tries this several times.
Thanks for your help!

**Comment by ben-z** [comment]
Did you try everything listed in the troubleshooting section?

> 5. General questions to consider before opening an issue:
>     1. Did you try wired mode?
>     1. Does your device show up in Finder's sidebar?
>     1. Did you click "trust" in Finder under the device tab?
>     1. Did you try unlocking your iPad before connecting?
>     1. Did you try restarting both devices and connecting again?
>     1. [Try these](https://github.com/ben-z/free-sidecar/issues/39#issuecomment-582487691)

**Comment by mithem** [comment]
Seems like clicking trust solved the issue 😅. Thanks a lot!

**Comment by rschluet** [comment]
I keep running into this issue.  I got it working today.  I had to disable ExpressVPN.
