### ISSUE TITLE
MacPro Late 2013 freezes after Sidecar launches on iPadPro 10.5in 2017

### ISSUE THREAD

**Issue by stolkunoff** [ben-z/free-sidecar#49]
MacPro  is Catalina 10.15.3 (19D76)
iPadPro is MQDT2RK/A iPadOS 13.3.1

In wired and wireless mode after selecting iPad in device list the screen blinks, 
Sidecar starts up on iPad. 
On iPad connection message hangs for a couple of seconds, then a black screen appears, MacPro freezes for about 2 minutes (keyboard, mouse and all apps not responding), then reboots.

Any suggestions?

**Comment by ben-z** [comment]
Waaaa I've never seen this problem before. Are you using stock hardware on the mac (graphics cards, etc)?

Which MacPro do you have?

The sidecar icon appears means the patched SidecarCore is signed correctly. This is probably an issue with Sidecar that's out of our control.

**Comment by stolkunoff** [comment]
MacPro6,1, 64 Gb, Catalina 10.15.3 (19D76)
6-Core Intel Xeon E5, 3,5 GHz
AMD FirePro D500, 3 Gb

all stock

**Comment by ben-z** [comment]
I'm not sure why the mac would freeze. If you are really keen then try it on a fresh install of macOS? Otherwise I'm out of ideas :(

**Comment by stolkunoff** [comment]
Is there any log file that may be used to see what is going wrong? Or some special execution modes?
I assume for the unix OS it has to be something on very deep level of commands to freeze system.

**Comment by stolkunoff** [comment]
Too many programs configured to experiment on a clean system )
I would like less invasive methods for diagnosing the situation.

**Comment by ben-z** [comment]
Have you installed any kernel extensions? I'm suspecting one of the programs on your computer is causing this issue. Could also try a fresh install on a separate hard drive and see if the problem occurs.

**Comment by stolkunoff** [comment]
I'll try fresh install on separate drive

**Comment by stolkunoff** [comment]
So ) I'v tried a fresh installation - same result.
Suppose that for my MacPro to work correctly, it is necessary not only to put a patch, but also use the old program code of SideCar. And possibly not only a SideCar, but also an earlier versions of MAC OS Catalina )

**Comment by ben-z** [comment]
Did it work on an earlier version of catalina?

**Comment by stolkunoff** [comment]
I haven’t tried it before, it may be worth working with earlier versions on an external drive, but in general I understand why the option is closed - complete freezes - this is code at the kernel level and new versions of OS use commands for new processors. It’s possible it’s too expensive to make different code versions for legacy Apple computers.

Thanks anyway for the experience.
