### ISSUE TITLE
ipad air 2 (A1566 ipad5,3) doesn't show up

### ISSUE THREAD

**Issue by newpeter20** [ben-z/free-sidecar#5]
Please fill in the template below to speed up the review process:

**Mac model: mac mini late 2012
**iPad model: ipad air 2

**Mac version** (optional):10.15.1
**iPad version** (optional):13

**Comments:**
ipad air 2 (A1566 ipad5,3) doesn't show up in this free-sidecar tool, the rest like ipad5,1 and ipad5,4 are there. Does blank orange box means already-supported?

**Comment by newpeter20** [comment]
![Screen Shot 2019-11-06 at 2 25 21 PM](https://user-images.githubusercontent.com/51392631/68273412-47a5bc00-00a1-11ea-9068-c3d1a60a5549.png)

**Comment by ben-z** [comment]
Oh no that looks like a UI bug that appeared in 10.15.1. I’ll fix it ASAP (should be within 24 hours)

**Comment by ben-z** [comment]
This should be fixed in [V1.2](https://github.com/ben-z/free-sidecar/releases/tag/v1.2)

**Comment by newpeter20** [comment]
it's fixed, now sidecar works (seems touch screen not supported), excellent! thank you!

**Comment by ben-z** [comment]
Np! Sidecar doesn't support touch screen in general (only supports Apple Pencil, that's probably why Apple restricted Sidecar to iPads with Apple Pencil support)
