### ISSUE TITLE
The device timed out

### ISSUE THREAD

**Issue by RohanKonchada** [ben-z/free-sidecar#51]
Please fill in the template below to speed up the review process:

**MacBook Air 8,2**
**iPad Air 2 5,3**
Whenever I try to connect my Mac to the my iPad, I keep getting an error that says the device timed out.

**Comment by ben-z** [comment]
This is a common issue. Have you tried wired? What have you tried from the troubleshooting section of README?

**Comment by MichaelSeaman** [comment]
MacBookPro11,2
iPad7,11

Hey Ben, I'm getting the same issue here. Both machines on the latest OS. 
I have attempted:

- Wired Mode
- Clicking "trust" under the device tab
- Unlocking the iPad before connecting
- Restarting both devices
- Reseting trust settings on iPad
- Trying mirroring display first
- Disabling Mac Firewall
- Logging out and back into iCloud on both devices
- Deleting preferences.plist

To no luck. Maybe you have some guess why? Thanks.

**Comment by ben-z** [comment]
@MichaelSeaman Thanks for providing a list of things that you've tried! I can't think of anything else to try other than making sure it's in wired mode by turning off wifi and bluetooth on the iPad.

**Comment by MichaelSeaman** [comment]
@ben-z Looks like that was able to do the trick. Disabling bluetooth was what I needed to do. Picture's a bit buggy on iPad (Possibly because of the older macbook pro hardware) but it's better than nothing. Thanks!

**Comment by Richy78** [comment]
if I disable bluetooth, MBP can't find my iPads
MBP 12,1 - 10.15.3 and IpadPro 6,7 13.3.1
same issue with Ipad 5,3 13.3.1

**Comment by ben-z** [comment]
@Richy78 That probably means your wired connection isn't getting picked up. Try the steps in the troubleshooting section of the readme, especially the part about logging into the same iCloud account and trusting the iPad in Finder.

**Comment by Richy78** [comment]
thanks @ben-z I've already trust the iPad and it uses the same iCloud account as the MBP. I'll try to disconnect iCloud from both device and reconnect. Also Do you think that I should use a certified MFI Apple cable?

**Comment by ben-z** [comment]
That would probably help. IIRC there was one issue about this and changing the cable/usb port resolved it.

**Comment by Richy78** [comment]
@ben-z disconnect/reconnect, reset settings and location fixed the issue. I can connect wirelessly and with wired but the resolution isn't very good

**Comment by ben-z** [comment]
Ya bad resolution is an ongoing issue :(. AFAIK there isn't anything we can do easily to solve this.

**Comment by nrukavkov** [comment]
The same problem with iPad 5 gen (6.11). I've tried to disable and enable Bluetooth . The same error =( 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/54890287/77232981-74242580-6bb5-11ea-812e-8aedd371e335.png">

**Comment by ben-z** [comment]
@nrukavkov  did you try wired?

**Comment by nrukavkov** [comment]
> @nrukavkov did you try wired?

Honestly, no. Because bought my new MacBook Pro 2019 few days ago and I don't have a wire to connect my iPad.

**Comment by ben-z** [comment]
Ah I see. A lot of (perhaps most) setups don’t support wireless sidecar currently. When you have a chance try wired. I feel pretty confident that it’s going to work since you have a new mac with an old iPad.

**Comment by nrukavkov** [comment]
> Ah I see. A lot of (perhaps most) setups don’t support wireless sidecar currently. When you have a chance try wired. I feel pretty confident that it’s going to work since you have a new mac with an old iPad.
> […](#)
> On Mar 22, 2020, at 2:05 AM, Nikita Rukavkov ***@***.***> wrote: ﻿ @nrukavkov did you try wired? Honestly, no. Because bought my new MacBook Pro 2019 few days ago and I don't have a wire to connect my iPad. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hello, now I try to use a wired connection. And I'm having a similar problem =(

<img width="704" alt="Screenshot 2020-04-02 at 11 39 07" src="https://user-images.githubusercontent.com/54890287/78228012-d561c800-74d6-11ea-984b-e1f4267322c4.png">

**Comment by ben-z** [comment]
Hmm it doesn't appear that you are connected over usb. Did you turn off both wifi and bluetooth?

**Comment by edwardcohen** [comment]
Would wireless work with the new iPad Pro (2020)?

**Comment by ben-z** [comment]
@edwardcohen Depends on what Mac you have. There's currently no infrastructure for tracking what devices work other than https://github.com/ben-z/free-sidecar/issues/55 so the best way is just to try it out.
