### ISSUE TITLE
Can't connect with my iPad Pro and MBA

### ISSUE THREAD

**Issue by tomclassmate** [ben-z/free-sidecar#52]
Please fill in the template below to speed up the review process:

**Mac model:**MBA 7,2  
**iPad model:**iPad Pro 11,

**Mac version** (optional):Mac OS 10.15.3
**iPad version** (optional):Pad OS 13.3.1

**Comments:**I have followed the instructions in the free-sidecar app,but I still can not see the Sidecar option,not even in wired mode.Can you help me with this?Thx a lot~

**Comment by ben-z** [comment]
Do you see a sidecar button in system preferences?

**Comment by Esinel** [comment]
@ben-z I have the same issue.

I did everything as stated. 

**MAC** model: 11,4
**iPad** model: iPad Pro 12.9 2018

As to answer your question, i dont have sidecar button in system preferences. 

Perhaps Apple patched this one as well?

**Comment by ben-z** [comment]
@Esinel Can you post your patched SidecarCore file?

**Comment by Esinel** [comment]
Yes of course

[SidecarCore.zip](https://github.com/ben-z/free-sidecar/files/4343516/SidecarCore.zip)

**Comment by ben-z** [comment]
@Esinel that file appears to be correctly patched for MacBookPro11,4. Did you do steps 7 and 8 without seeing errors? Did you make sure [MacBookPro11,4](https://everymac.com/ultimate-mac-lookup/?search_keywords=MacBookPro11,4) is the correct model number?

**Comment by Esinel** [comment]
@ben-z Yes i got no errors in the process.

My MBP is this one specifically: 
https://support.apple.com/kb/SP719?locale=en_GB

**Comment by ben-z** [comment]
That's really weird. It still works on my 2015 13" MBP. What version of Catalina do you have?

**Comment by Esinel** [comment]
When did you patch yours?

My Catalina is on 10.15.3
take a look

<img width="529" alt="Screenshot 2020-03-18 at 7 22 28 PM" src="https://user-images.githubusercontent.com/11630337/76993927-f14d6180-694d-11ea-927c-4b5c501d7931.png">

**Comment by ben-z** [comment]
I’m on the same version. Patched it a while ago.

I’m not sure how to debug this lol. Perhaps try opening the SidecarCore file in /System/... and see if the file is patched? That would eliminate the possibility of not copying the file correctly.

**Comment by Esinel** [comment]
I will try it tommorow and let you know!

**Comment by Esinel** [comment]
Sorry but how can i check it file is patched?  I know i need a hex editor, but what should i do?

**Comment by tomclassmate** [comment]
> Do you see a sidecar button in system preferences?

No，I didn't see it。

**Comment by ben-z** [comment]
> Sorry but how can i check it file is patched?  I know i need a hex editor, but what should i do?

Don’t need a hex editor. Open free-sidecar and click the button to select a sidecarcore file. Select the one in /System/...
