### ISSUE TITLE
Add to Read Me / Steps: Requirement: Xcode command line tools. Hint: Picture flickering for many models

### ISSUE THREAD

**Issue by martzell** [ben-z/free-sidecar#53]
**Mac model:** MacBook Pro (Retina, 15-inch, Mid 2015)
**iPad model:** iPad 5th Generation • iPad6,11 

**Mac version** (optional): 10.15.3 (19D76)
**iPad version** (optional): 13.3.1 (17D50)

**Comments:**
Installed Xcode command line tools are a must if you don't want to crash all programms every second; should be written in the Steps / Read Me.

In addition, a hint would be helpful that Sidecar is actually not usable because of the poor flickering picture. Are all models with this combination affected: Mac without HEVC and iPad with HEVC hardware?
![image](https://user-images.githubusercontent.com/19435610/73785732-dd66eb00-4765-11ea-93ab-98afc17002cc.gif)

**Comment by ben-z** [comment]
I was hoping that people would see an error in step 8 and fix the error but apparently not lol. That's a good idea I will add to the readme.

**Comment by ben-z** [comment]
Fixed in https://github.com/ben-z/free-sidecar/commit/a7b20b323dc3d628648ee58e8507391d1cd9b976

**Comment by mihaisavezi** [comment]
@martzell - Did you fix the flickering ?

**Comment by martzell** [comment]
Don't know how or if possible at all. I've started a list of non-working Mac iPad combinations:

https://github.com/ben-z/free-sidecar/issues/55
