### ISSUE TITLE
List of not working Mac iPad combinations

### ISSUE THREAD

**Issue by martzell** [ben-z/free-sidecar#55]
![image](https://user-images.githubusercontent.com/19435610/73785732-dd66eb00-4765-11ea-93ab-98afc17002cc.gif)

Are all models with this combination affected by flickering? Mac without HEVC and iPad with HEVC hardware?

- **Mac:** 6th Generation Intel processor is needed for HEVC hardware encoding: • MacBook Pro 2016 or later • MacBook Air Retina.
  - **iPad:** A9 processor necessary for HEVC hardware decoding: iPad (2017) 5th Generation and all iPads supporting Pencil.

Following combinations are not working. Please Copy & Paste from "About This Mac" and Finder / iTunes / iPad Settings » General: iPad info (click on model name to see technical model name; unfortunately no Copy & Paste possible here).

- MacBook Pro (Retina, 15-inch, Mid 2015) • 2,2 GHz Quad-Core Intel Core i7 • Intel Iris Pro 1536 MB
  - iPad (2017) 5th Generation • iPad6,11

**Comment by ben-z** [comment]
Thanks for this, but I'm not sure if it's worth maintaining at the moment (takes too much effort to gather the list). I'm happy to keep this open though.

**Comment by martzell** [comment]
My idea is to have a place for a community written wiki page / list, which combinations are working / not working.

Could the original question be answered? If the answer yes is true this should be stated in the red me before installing. »Are all models with this combination affected by flickering? Mac without HEVC and iPad with HEVC hardware?

Mac: 6th Generation Intel processor is needed for HEVC hardware encoding: • MacBook Pro 2016 or later • MacBook Air Retina.
iPad: A9 processor necessary for HEVC hardware decoding: iPad (2017) 5th Generation and all iPads supporting Pencil.«

**Comment by ben-z** [comment]
Only older Macs with newer iPads seem to be affected. I haven't received any issues about older iPads.

It's pretty difficult at the moment to create a list where people would actually contribute to unless the list already exists. At the moment this can only be achieved by going through all of the old issues and cherry-pick out a list of models with their issue numbers attached.

**Comment by newmediacrew** [comment]
> Only older Macs with newer iPads seem to be affected. I haven't received any issues about older iPads.
> 
> It's pretty difficult at the moment to create a list where people would actually contribute to unless the list already exists. At the moment this can only be achieved by going through all of the old issues and cherry-pick out a list of models with their issue numbers attached.

I can confirm that "Only older Macs with newer iPads seem to be affected" is correct. I am trying to use an MacBook Pro (Retina, 13-inch, Early 2015) with a 6th gen iPad. And get the same screen flickering as @martzell is showing.

**Comment by xx-arch** [comment]
I can confirm a trouble as well, MacBook Pro Mid 2015 doesn't work with iPad 7th generation.

**Comment by Scoty** [comment]
Thanks guys for letting me know - I was planing to buy iPad Pro 11" (2020) and use it with my MacbookPro 11,4 (Retina, Mid 2015) but reading this it seems I should also buy new MacbookPro if I want to use sidecar, so I will not get the iPad atm. IMO the incompatibility(causing flickering) between devices with hardware support of HEVC and software only support of HEVC should be pointed out in the README
