### ISSUE TITLE
the codesign_allocate helper tool cannot be found or used

### ISSUE THREAD

**Issue by ghost** [ben-z/free-sidecar#57]
Mac model:iMac19,1
iPad model:iPad Air 2

Mac version:10.15.3
iPad version:13.3.1

sh: line 1:   569 Killed: 9               /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find codesign_allocate 2> /dev/nullcodesign_allocate: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find codesign_allocate 2> /dev/null' failed with exit code 35072: (null) (errno=No such file or directory)
xcode-select: Failed to locate 'codesign_allocate', requesting installation of command line developer tools.
/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: the codesign_allocate helper tool cannot be found or used

[SidecarCore.zip](https://github.com/ben-z/free-sidecar/files/4362334/SidecarCore.zip)

Help

**Comment by ben-z** [comment]
Install/update Xcode dev tools. Instructions are in the readme and in past issues.

**Comment by ghost** [comment]
Thanks. 
Xcode 11.3.1
Xcode command line is the latest
Still that same error

**Comment by ben-z** [comment]
What happens when you type `xcode-select --install`?

Have you tried uninstalling and reinstalling Xcode?

**Comment by ghost** [comment]
xcode-select —install. A Installation window .Normal installation
I tried uninstalling and reinstalling Xcode，Command Line Tools
Still not working

**Comment by ben-z** [comment]
> A Installation window

You should see `xcode-select: error: command line tools are already installed, use "Software Update" to install updates` instead. It probably means that the command line tools are not properly installed.

![image](https://user-images.githubusercontent.com/5977478/77226422-a9495d00-6b4e-11ea-92f5-6edfa89885c2.png)
