### ISSUE TITLE
Does a clean install of Mac Os revert everything back to normal?

### ISSUE THREAD

**Issue by rtabe** [ben-z/free-sidecar#58]
Dear Ben!

Does a clean install of Mac Os, followed by a time machine restoration, revert everything back to standard?

Thank you very much in advance!

**Comment by ben-z** [comment]
Yep.

Or you can just unpatch the SidecarCore file. Instructions are in the "Troubleshooting" section of the README:

```
sudo cp ~/Downloads/SidecarCore.bak /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore

sudo codesign -f -s - /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
```
