### ISSUE TITLE
Your Device Timed Out

### ISSUE THREAD

**Issue by hiokok** [ben-z/free-sidecar#6]
Please fill in the template below to speed up the review process:

**Mac model:** MacBook Air Early-2015
**iPad model:** iPad 5th generation (2017)

**Mac version** (optional): macOS Catalina
**iPad version** (optional): iPadOS

**Comments:** it says "Your Device" Timed Out every time I try to do it

**Comment by ben-z** [comment]
Here's a list of things to help troubleshoot:
1. Did you try wired mode?
1. Does your device show up in Finder's sidebar?
1. Did you click "trust" in Finder under the device tab?
1. Did you try unlocking your iPad before connecting?
1. Did you try restarting both devices and connecting again?

Also can you include the specific versions of macOS and iPadOS?

**Comment by zigamagoon** [comment]
This is also happening to me, though most of the time when I select my iPad Pro from the menubar or Preferences, literally nothing happens.

Mac model: MacBook Pro 11,3 (Retina, 15-inch, Mid 2014) 
iPad model: iPad Pro (11-inch)

Mac version (optional): macOS Catalina 10.15.1
iPad version (optional): iPadOS 13.2.2

Did you try wired mode? Yes, USB A to USB C
Does your device show up in Finder's sidebar? Yes
Did you click "trust" in Finder under the device tab? Yes, trusted and can sync
Did you try unlocking your iPad before connecting? Yes
Did you try restarting both devices and connecting again? Yes
Also can you include the specific versions of macOS and iPadOS? 10.15.1 and 13.2.2

**Comment by apple2373** [comment]
Mac: MacBookPro12,1
Mac OS: 10.15.1
iPad: iPad9.7  
iPad OS: 13.2.3
I have the same issue. I wonder if the MFI matters or not. My cable is not MFI certified.
