### ISSUE TITLE
Not working on all admin accounts

### ISSUE THREAD

**Issue by mazoma** [ben-z/free-sidecar#60]
**Mac model: MBP 15in 2017 running Catalina**
**iPad model: iPad Air 2 running iOS 13.3**

I've been able to correctly setup sidecar for one of two admin accounts...but not for the second. Any idea? I'm a real novice

**Comment by ben-z** [comment]
This patch should be system-wide and user-account-independent. See the general troubleshooting instructions (specifically the part about using the same iCloud account).

**Comment by mazoma** [comment]
Thank you ben-z!! As you suggested it was just a amateur of setting up the same iCloud account. Cheers
