### ISSUE TITLE
Disappear icons after apply patch

### ISSUE THREAD

**Issue by jgiunta** [ben-z/free-sidecar#62]
Macbook Air 2017 Catalina 10.15.4
iPad 7th Generation

Hello guys,

I follow all steps, including the exeptions for my version of Catalina, but when I reboot I can see anymore the Wifi, Spotlight, Date and other icons on the top bar, but the Sidecar icon appears on my preferences.

Can any help me ?

Thanks

**Comment by ben-z** [comment]
Sounds like the `amfi_get_out_of_my_way=0x1` boot flag wasn't in effect. Can you verify:
1. SIP is disabled:
  ```
  > csrutil status
  System Integrity Protection status: disabled.
  ```
2. Ensure that the boot flag is set properly:
  ```
  > nvram boot-args
  boot-args amfi_get_out_of_my_way=0x1
  ```

**Comment by jgiunta** [comment]
Yes of course, (In recovery mode)

1) System Integrity Protection status: disabled
2) It's fine, return the same line you wrote before

Maybe helps, when I try to sign the file I get:

replacing existing signature
the codesign_allocate helper tool cannot be found or used (I have xcode installed)

Thanks!

**Comment by ben-z** [comment]
Oh ya that's a problem LOL. Try the troubleshooting steps here: https://github.com/ben-z/free-sidecar/issues/57 an in the troubleshooting section in the README. Also try reinstalling Xcode.

**Comment by jgiunta** [comment]
Hello again,

I can't find xcode-install on recovery mode and another thing, I don't have my root path mounted on /

In recovery mode:

df -h

Filesystem     Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s1  1.9Gi  1.2Gi  638Mi    67%   47933 4294919346    0%   /
devfs         207Ki  207Ki    0Bi   100%     716          0  100%   /dev
/dev/disk3     10Mi  836Ki  9.2Mi     9%      23 4294967256    0%   /private/var/log
/dev/disk4     10Mi  256Ki  9.8Mi     3%       3 4294967276    0%   /private/var/log/dm
/dev/disk5    512Ki  144Ki  368Ki    29%       5 4294967274    0%   /Volumes
/dev/disk6    512Ki  144Ki  368Ki    29%       8 4294967271    0%   /private/var/tmp
/dev/disk7    512Ki  156Ki  356Ki    31%      15 4294967264    0%   /private/var/run
/dev/disk8    2.0Mi  148Ki  1.9Mi     8%       6 4294967273    0%   /private/tmp
/dev/disk9    512Ki  140Ki  372Ki    28%       2 4294967277    0%   /System/Installation
/dev/disk10   512Ki  296Ki  216Ki    58%      27 4294967252    0%   /private/var/db
/dev/disk11    12Mi  4.4Mi  7.6Mi    37%      81 4294967198    0%   /private/var/folders
/dev/disk12   4.0Mi  188Ki  3.8Mi     5%      18 4294967261    0%   /private/var/root/Library
/dev/disk14   2.0Mi  140Ki  1.9Mi     7%       2 4294967277    0%   /private/var/root/Library/Containers
/dev/disk15   512Ki  172Ki  340Ki    34%      13 4294967266    0%   /Library/Preferences
/dev/disk16   2.0Mi  140Ki  1.9Mi     7%       2 4294967277    0%   /Library/Preferences/Logging
/dev/disk17   512Ki  156Ki  356Ki    31%       6 4294967273    0%   /Library/Preferences/SystemConfiguration
/dev/disk18   1.0Mi  188Ki  836Ki    19%       8 4294967271    0%   /Library/Keychains
/dev/disk19   512Ki  140Ki  372Ki    28%       2 4294967277    0%   /Library/Security/Trust Settings
/dev/disk20   6.0Mi  172Ki  5.8Mi     3%       2 4294967277    0%   /private/var/tmp/RecoveryTemp
/dev/disk21   6.0Mi  172Ki  5.8Mi     3%       2 4294967277    0%   /private/var/tmp/OSISPredicateUpdateProductTemp
/dev/disk22   512Ki  140Ki  372Ki    28%       2 4294967277    0%   /private/var/tmp/InstallerCookies
/dev/disk23   2.0Mi  140Ki  1.9Mi     7%       2 4294967277    0%   /Library/Logs/DiagnosticReports
/dev/disk2s1  466Gi   63Gi  391Gi    14% 1809178 4880008262    0%   /Volumes/Macintosh HD - Datos
/dev/disk2s2  466Gi   10Gi  391Gi     3%  487316 4881330124    0%   /Volumes/Macintosh HD

The root filesystem is in /Volumes/Macintosh HD and the home folder on /Volumes/Macintosh HD - Datos

So I copy SidecarCore file with this command:

cp /Volumes/Macintosh\ HD\ -\ Datos/Users/jorge/Downloads/SidecarCore /Volumes/Macintosh\ HD/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore

Then when I try to sign this file I get:

codesign -f -s - /Volumes/Macintosh\ HD/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
/Volumes/Macintosh HD/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: replacing existing signature
/Volumes/Macintosh HD/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: the codesign_allocate helper tool cannot be found or used

Next I try xcode-select --install and I get "Command not found"

Xcode is installed on my Macbook because I compiled my apps a hours ago.

Can I try anymore ?

Thanks

**Comment by ben-z** [comment]
Have you tried googling `xcode-select "--install" Command not found`?

This may help https://stackoverflow.com/a/29877782/4527337

**Comment by jgiunta** [comment]
No really, because the problem is not a miss file. The xcode-select exist when I boot on normal mode. It's only in recovery where I can't find the command.

In my opinion the problem are on separate volumes, in Readme you write to re mount "/" and my root partition in recovery mode is not my really "/", are /Volumes/Macintosh HD.

Thanks

**Comment by ben-z** [comment]
Oh don't sign `SidecarCore` in recovery. Sign it in the normal mode. Recovery is only for enabling/disabling SIP.

**Comment by jgiunta** [comment]
oh man... was that ! I never read reboot into MacOS ! It's working !

My fault. Sory !

Thanks

**Comment by ben-z** [comment]
Awesome :)
