### ISSUE TITLE
MacBook Messed Up

### ISSUE THREAD

**Issue by Isaacm05** [ben-z/free-sidecar#63]
Please fill in the template below to speed up the review process:

**Mac model:MacBook air 2017**
**iPad model:iPad 6th Gen**

**Mac version** (optional):
**iPad version** (optional):

**Comments:**
My MacBook was having issues opening any apps. I tried to troubleshoot with step six, which did not work so I went to step 8. I went through the whole process, but nothing changed. What do I do?

**Comment by ben-z** [comment]
Can you share your `/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore`?

**Comment by Isaacm05** [comment]
Well I fixed it by reinstalling mac. But I remember that it basically did nothing after I entered that command
