### ISSUE TITLE
iPad pro 2020  blurred screen

### ISSUE THREAD

**Issue by tuine** [ben-z/free-sidecar#65]
**Mac model: MacBookPro11,4 （MacBook Pro (Retina, 15-inch, Mid 2015)）**
**iPad model: iPad pro 2020 12.9**

**Mac version** (optional):10.15.4
**iPad version** (optional): 13.4

**Comments:**
the iPad  blurred screen

**Comment by ben-z** [comment]
Can you provide more details? A picture/screenshot of the blurred screen would be cool. Likely not something that we can fix though (similar to all of the other quality tickets).

**Comment by tuine** [comment]
@ben-z 

![IMG_2439 2](https://user-images.githubusercontent.com/9445048/77874572-e2d14500-727f-11ea-833c-81cf72d68c8d.jpg)
![IMG_1846](https://user-images.githubusercontent.com/9445048/77874579-e8c72600-727f-11ea-827f-67cb36521410.jpg)

The screen keeps flashing. There is another problem: System will crash when I use the original SidecarCore ( ~/Downloads/SidecarCore.bak). But system can boot normally when use the file I backed up to other place. 

 I found the extra symbol(@) :
-rwxr-xr-x@ 1 myname  staff   284K  3 30 11:45 /Users/myname/Downloads/SidecarCore.bak

**Comment by ben-z** [comment]
Hm that’s weird. Can you make sure the .bak file has never been modified?

**Comment by tuine** [comment]
Yes ,I just copied it from the first step.

**Comment by ben-z** [comment]
Is the only difference between SidecarCore.bak in your downloads folder and your backup the [extended attributes](https://unix.stackexchange.com/questions/106642/what-does-the-at-symbol-mean-on-osx-ls)?

**Comment by ben-z** [comment]
Where did you save your other backup?

**Comment by tuine** [comment]
Sorry, I can't reproduce this problem, because I found that the current SidecarCore also has "@". I just remember the  system start kept crashing when I use the file backed up in the first step (enable SIP,  but It's ok when SIP disabled ) and then I suddenly thought that I also backed up this file, it start normally  when I use this.

I'm not sure if this is the reason. I tried another :
example:
<img width="786" alt="QQ20200331-003033@2x" src="https://user-images.githubusercontent.com/9445048/77937452-ee0b8b80-72e6-11ea-8bdc-98276f3af374.png">

Is there a solution to the problem of "the blurred screen ",Thanks

**Comment by ben-z** [comment]
The patch does not work on 10.15.4 with SIP enabled. This is explained in the README and https://github.com/ben-z/free-sidecar/issues/59#issuecomment-603953953.

No solution currently for quality issues. It's not as straight forward as simply editing a blacklist.

**Comment by mattiLeBlanc** [comment]
I have a similar issue with my Macbook Pro 2013 Retina and my new ipad 7th gen.
I think it has to do with airplay and refresh mode or something. I agree not something you can easily fix. This is probably a hardware thing in my Macbook which why it wasn't supported from the get go.
