### ISSUE TITLE
Touch Screen not working on IPAD AIR 2

### ISSUE THREAD

**Issue by Egoxboy** [ben-z/free-sidecar#66]
Please fill in the template below to speed up the review process:

**Mac model:** Mac book pro 2018
**iPad model:** IPAD AIR 2

**Mac version** (optional):10.15.4
**iPad version** (optional):13.4

**Comments:**
I followed all the instruction and I can now use the IPAD as a sidecar device. 
But the touchscreen ON THE TOUCH BAR doesn't work on the IPAD . Do you have any idea? Thanks a lot.

**Comment by ben-z** [comment]
Touch input (through tapping) is not a feature of Sidecar. Only gestures and apple pencil are supported: https://support.apple.com/en-ca/HT210380.

**Comment by Egoxboy** [comment]
Thnak you very much, but I meant the touchbar... I thought it worked.

**Comment by ben-z** [comment]
The Touch Bar should work. What's the behaviour that you are seeing right now?

**Comment by Egoxboy** [comment]
The touch bar on the ipad simply doesn't reply to the touch. The lateral bar is working, but not the touch bar. I really don't know what it could be the problem, and how to fix it.

**Comment by ben-z** [comment]
That's really weird. I don't know where to start to debug. Perhaps turn off the Touch Bar and turn it on again (through system preferences)?
