### ISSUE TITLE
Only wired connection working

### ISSUE THREAD

**Issue by goekhan-klc** [ben-z/free-sidecar#67]
Please fill in the template below to speed up the review process:

**Mac model:**MacBook Pro 13' 2019
**iPad model:** iPad5,1

**Mac version** (optional): Catalina 10.15.3
**iPad version** (optional):13.3.1

**Comments:** Hey. After some troubleshooting i figured out how to get sidecar working on my ipad mini 4. But it only works with an wired connection. Can you give me some tips so it may be working on wireless too?

**Comment by ben-z** [comment]
I'm unaware of a fix to make wireless working. You could search the past issues but AFAIK none of them reached any concrete conclusions.

**Comment by goekhan-klc** [comment]
Okay. Thanks for your help!
