### ISSUE TITLE
Crashed finder 

### ISSUE THREAD

**Issue by teddybearrohan** [ben-z/free-sidecar#68]
Re enabled system integrity and restarted to be bombarded with messages saying finder quit unexpectedly because sidecarcore is missing. I cannot open any apps except freesidecar and terminal. 

Edit: when I try to re copy from downloads, it gives the error “read only file system”

Edit 2: tried to copy the backup, still getting “finder quit unexpectedly”
Am I all out of options except reinstalling?
I need my computer for a video call in 2 hours

**Comment by ben-z** [comment]
Are you 10.15.4? There's a note in README that says not to reenable SIP on 10.15.4.

**Comment by ben-z** [comment]
Readonly filesystem is because you didn't mount the filesystem as read-write:

```
sudo mount -uw /
```

**Comment by ben-z** [comment]
That step requires SIP off ^

**Comment by teddybearrohan** [comment]
Even after disabling SIP and restarting finder still doesn’t work

**Comment by teddybearrohan** [comment]
I am on 10.15.4 on 2019 MacBook air

**Comment by ben-z** [comment]
Did you do the extra step:

> macOS Catalina 10.15.4+ users: Add amfi_get_out_of_my_way=0x1 to NVRAM boot flags, then skip step 9.

**Comment by teddybearrohan** [comment]
> Did you do the extra step:
> 
> > macOS Catalina 10.15.4+ users: Add amfi_get_out_of_my_way=0x1 to NVRAM boot flags, then skip step 9.

How do I do that

**Comment by ben-z** [comment]
Instructions are linked from the README.

**Comment by teddybearrohan** [comment]
I want to get back to the way it was before, not patched, SIP on. How do I get back other than reinstall?

**Comment by ben-z** [comment]
In that case follow the instructions in the troubleshooting section. I'll summarize it here:
1. Disable SIP
2. Mount the partition as read-write
3. Copy the backup file into the system folder
4. Enable SIP

**Comment by teddybearrohan** [comment]
I just did that and my Finder still will not start. I’m going to reinstall.

**Comment by ben-z** [comment]
Hmmm did you happen to run the backup step more than once and overwrote the backup file with the patched file?

**Comment by teddybearrohan** [comment]
Yes, that is most likely what happened. I’m going to just reinstall MacOS and use my iPad the rest of the day. Currently backing up all my important files.

**Comment by ben-z** [comment]
Here's my backup file from 10.15.4 MBP 13" 2019:

[SidecarCore.bak.zip](https://github.com/ben-z/free-sidecar/files/4417061/SidecarCore.bak.zip)

Can't guarantee it works but probably worth a try before you reinstall—shouldn't break things any more than they are now.

**Comment by teddybearrohan** [comment]
I will try that.

**Comment by teddybearrohan** [comment]
Thanks so much, it worked! You saved me several hours of pain and suffering

**Comment by ben-z** [comment]
Awesome :)
