### ISSUE TITLE
Error 32002 over USB connection

### ISSUE THREAD

**Issue by lyinghawaiian** [ben-z/free-sidecar#7]
Please fill in the template below to speed up the review process:

**Mac model: MacBook Pro (Retina, 13-inch, Early 2015)
**iPad model: iPad (6th generation)

**Mac version** (optional): 10.15.1
**iPad version** (optional): 13.2.2

**Comments: Quality is poor over wireless connection but connecting through USB prompts the 32002 error (error does not occur over a wireless connection)

**Comment by ben-z** [comment]
Did you “trust” your device from the finder window? When connecting through USB the iPad should show up in finder. Click into it and see if it prompts you to trust it

**Comment by lyinghawaiian** [comment]
The MacBook was previously a trusted device. Reset the trust settings after the setup and still produces the same problems.

Seems to be an issue with the bit rate as the display is much clearer when displaying low bit rate images. Could this be an issue with hardware limitation of older devices as resource usage seems much higher than expected.

**Comment by ben-z** [comment]
It could be that the MBP is not keeping up with sending high quality pictures to the iPad. We've seen this in https://github.com/ben-z/free-sidecar/issues/4 and a few reports from Reddit. Try the workaround in https://github.com/ben-z/free-sidecar/issues/4 if you can!

**Comment by Bechrissed** [comment]
I'm also seeing a 32002 error over USB connection. My devices are:

- Macbook pro 16"  (hardware model: MacBookPro16,1)
- iPad Air 2: (hardware model: iPad5,3)

I have enabled iPad 5.3 through the "free-sidercar" application an executed all steps without errors. How to debug further?

*update*

MacOS version: 10.15.1
iPadOS version: 13.2.3

**Comment by ben-z** [comment]
@Bechrissed Your setup is very similar to mine! I have MBP 2019 and iPad Air 2.

Which cable do you use to connect your iPad to the computer? Did you try turning off wifi/bluetooth to make sure it's using wired connection? Did you make sure that the iPad is connected and trusted in Finder?

**Comment by Bechrissed** [comment]
Hi @ben-z, i've used the apple AV adapter and usb to lightning from iPad.
I didn't do the last two checks. Will try tonight and see if it works. Thanks.

**Comment by Bechrissed** [comment]
Ok, got it working by turning off bluetooth and wifi. After I got it working i can now turn on wifi and bluetooth and it keeps working. Only when connected through USB though. Thanks for your work and the help.

**Comment by MrBokeh** [comment]
Hi @Bechrissed I can't get mine working (early 2013 rMBP 15") even turning things off, what was the sequence and settings that you have done? also which iPad did you use? I have the iPad 9.7"  2018 (non-pro)

**Comment by Bechrissed** [comment]
@MrBokeh i've followed the instructions as given in the readme. After that:

1. disconnect USB/lightning cable
2. turn off bluetooth and wifi on iPad
3. connect USB/lightning cable
4. open sideCar in MacOS system preferences
5. select your  iPad

After you've established a connection successfully once it isn't necessary anymore to disable wifi or bluetooth. I have an iPad Air 2.

**Comment by LukasMFR** [comment]
Hi,
I found a fix (at least for me)
Here are the devices I have  : 
MacBook Pro 15" mid-2012 MacBookPro9,1
iPad Pro 10.5" WiFi
I had the 32002 error and I reseted the trusted computers on my iPad (Settings->General->Reset->Reset Location services and ...)
And now it works BUT the quality is quiet low (using it on wired) and my Mac kinda feels unresponsive
Hope it helps !!!
