### ISSUE TITLE
Restore AMFI too ?

### ISSUE THREAD

**Issue by monstermunchguy** [ben-z/free-sidecar#72]
**Mac model:**MacBook Air 13' 2017

Mac version (optional): Catalina 10.15.4

Comments:
Hi all,
I'm new here and new to mac so forgive me if I say random stuff ;)
I've just been through the whole process on MacAir 7.2 Catalina 10.15.4
Everything went fine and followed the extra step amfi_get_out etc...
No error messages at all everything went fine
I know have access to Sidecar but I have none of the system icons appearing anymore at the top right corner ie: clock, wifi, bluetooth etc.. They are all unchecked in the sys prefs and I can recheck them but when I apply they uncheck themselves automatically.
I want to restore the original sidecarcore (I have found out how to do that) 
What I need to know is, before restoring this file and enabling csrutil again do I need to remove that amfi_get_out... from the NVRAM boot flags? If yes what would be the correct cmd to type in terminal?
Thanks

**Comment by ben-z** [comment]
To delete the NVRAM boot flag:

```
nvram -d boot-args
```

(you may need to add `sudo` in the front)

It's weird that you are seeing status bar icon issues. Did you properly sign the binary (step 8), properly set the boot flag (can check with `nvram boot-args`) and keep SIP disabled?

**Comment by monstermunchguy** [comment]
ah! ok I know was a typing mistake! 
I deleted the NVRAM boot flag with your command and re-added amfi command and rebooted
All is fine now ! Now let's try the iPad and see how this works :)
Thanks a lot !!!
