### ISSUE TITLE
Screen sharing not working after freeing sidecar

### ISSUE THREAD

**Issue by benbravo1** [ben-z/free-sidecar#73]
Hi Ben,

Impossible to share the screen on video conferencing app (zoom in my case) with the patched SideCarCore file in place. Zoom won't show up for allowing in the privacy preferences pane. Had to revert to default to be able to do it.

Thanks for looking into it. 

**MacBook Pro (Retina, 15-inch, Mid 2014)**
**11-inch iPad Pro 2018**

**macOS Catalina 10.15.4**
**ipadOS 13.4**

**Comment by ben-z** [comment]
Whoa I'm not aware of this. Will try it in a couple of days. Thanks for bringing it up!

**Comment by ben-z** [comment]
I haven't tried Zoom but Google hangouts screen sharing has been working fine for me with patched SidecarCore.
