### ISSUE TITLE
MacBook Pro not finding iPad

### ISSUE THREAD

**Issue by pescalec** [ben-z/free-sidecar#74]
MacBook Pro Retina 15inch late 2013
iPad MD510TY/A (iPad 4)

macOS Catalina 10.15.4
iOS 10.3.3

Hello,
I have followed the steps specified on your tutorial and the SideCar app showes up on my Mac.
However, no connection can be reached, neither through AirPlay or cable.

The iPad does not show up on SideCar App
I have tried:
- ON/ OFF the wifi and Bluethoot
- Disable FireWall
- Sign in and out of iCloud on both devices
- Delete preferences.plist
- Set iPad as trusted device

I hope you can give me a hand. Thank you in advance!

**Comment by pescalec** [comment]
Yes, I´ve went through both things!

**Comment by ben-z** [comment]
Hmm that's weird. Does the iPad show up in Finder when you connect it through USB? If not then try a different wire.

**Comment by pescalec** [comment]
Yes it does! The device is detected and authorized.

**Comment by ben-z** [comment]
Wait a second you are on iOS 10? Sidecar is only supported on iPadOS 13.

**Comment by pescalec** [comment]
Ah! That makes sense, I had no idea. Thank you for giving a hand
