### ISSUE TITLE
time out message

### ISSUE THREAD

**Issue by DiViDiHN** [ben-z/free-sidecar#75]
Please fill in the template below to speed up the review process:

**Mac model: MacMini7,1
**iPad model: iPad Pro 11" (2018)

**Comments:**
SideCar icon appears in the menu and system properties. But if I click on it no connection is established. A message appears that a timeout happens.
MacMini and iPad are in the same network and I use the same AppleID. Bluetooth is enabled. 

Can u help?

**Comment by ben-z** [comment]
Did you try wired?

**Comment by DiViDiHN** [comment]
Yes we tried it even with a cable. Trust relation is established. Any debugging what I can do?
OS: MacOS 10.15.3 and iPadOS 13.3.1

**Comment by ben-z** [comment]
Did you make sure that Sidecar was using the USB connection instead of wireless by disabling bluetooth and WIFI?

**Comment by DiViDiHN** [comment]
Now I tried it. I turned off BT and WiFi on the iPad. In the sidecar panel (system settings) the iPad is still visible. And when I choose it the same result appears (the timeout message). If I turned off BT even on the MacMini the iPad is not visible in the Sidecar panel.

**Comment by ben-z** [comment]
Hmm I'm not sure what else to do if you've exhausted every troubleshooting step.

**Comment by prurigro** [comment]
I had the same issue until I disabled wifi on the ipad
