### ISSUE TITLE
iPad8,5 isn't listed

### ISSUE THREAD

**Issue by frankywashere** [ben-z/free-sidecar#76]
Please fill in the template below to speed up the review process:

**Mac model:**
Macbookpro9,1
**iPad model:**
ipad 8,5/8,6
**Mac version**:
10.15.4
**iPad version**:
13.4.1
**Comments:**
I don't see my ipad listed in freeside car when patching sidecarcore. anyway to add this?

Frank

**Comment by ben-z** [comment]
iPad Pros are officially supported. Just patch your Mac.

**Comment by Taeil2** [comment]
I'm having the same issue. My iPad model is 8,1 but it's not an option in free-sidecar.

![image](https://user-images.githubusercontent.com/2238799/80177785-4c641b00-85c2-11ea-9977-370270782553.png)

![image](https://user-images.githubusercontent.com/2238799/80177815-5f76eb00-85c2-11ea-9b77-a8ee087cd5bd.png)

**Comment by ben-z** [comment]
There's no need to patch your iPad because it's officially supported: https://support.apple.com/en-ca/HT210380#systemrequirements
