### ISSUE TITLE
iPad7, 5 isn’t listed

### ISSUE THREAD

**Issue by 1014185nou** [ben-z/free-sidecar#77]
Please fill in the template below to speed up the review process:

**Mac model:** MacBookAir7,1
**iPad model:** iPad7, 5

**Mac version**: 10.15.4
**iPad version**: 13.4.1

**Comments:**
iPad 7, 5 isn’t listed under devices to enable.

**Comment by ben-z** [comment]
iPad 6th gen is officially supported. There's no need to remove it from the blacklist because it doesn't exist in the blacklist.

**Comment by 1014185nou** [comment]
Thanks for clearing that up. I don't know why I didn't think of that.
