### ISSUE TITLE
Ipad 6,8 is not listed and screen definition is very poor

### ISSUE THREAD

**Issue by chrisswitch470** [ben-z/free-sidecar#78]
Please fill in the template below to speed up the review process:

**Mac model: 15,1
**iPad model: 6,8

**Mac version**: 10.15.4
**iPad version**: 13.3

**Comments:**
Hi,  it all works after following the guides and setting the nvram flags except the screen definition in the iPad is very poor - even when wired. I enabled 6,11 and 6,12 in the sidecar patch file.
Was this correct?
Thanks for working on this - I really want to have sidecar working to give me the space

**Comment by ben-z** [comment]
iPad Pros are officially supported so it isn't listed in the blacklist. The quality issue is common among iPad Pros + older Macs, probably because older Macs lack hardware HEVC encoding/decoding. There's no need to enable 6,11 and 6,12.

**Comment by chrisswitch470** [comment]
Did the reinstall without enabling the iPad and it worked however the screen quality on the iPad remains an issue - as you say a function of HEVC.  I will close this issue.  Thanks again
