### ISSUE TITLE
Imovie FaceTime camera not working after nvram flag set

### ISSUE THREAD

**Issue by chrisswitch470** [ben-z/free-sidecar#79]
Please fill in the template below to speed up the review process:

**Mac model:  IMAC 15,1
**iPad model: pro 8,8

**Mac version**:  10.15.4
**iPad version**: 13.3

After installing the patch and setting the nvram flags, the iPad connected - although iPad screen definition is not great but my FaceTime (built in) camera stopped working and I could not record a video.  By undoing the flags th camera worked again but Safari and a few other things then stopped.
Have reverted back to original config and will try again

**Comment by ben-z** [comment]
I cannot reproduce this on my MBP '19. My FaceTime camera still works even with the NVRAM flag set. Let's keep this open for a while to see if others have run into the same problem.

**Comment by chrisswitch470** [comment]
I have just repeated the installation and there's no problem with FaceTime camera on iMovie this time so I think this must have been something I did out of order or another cause.  Will close this.  Thanks again
