### ISSUE TITLE
iPad Pro 7,3 missing in UI List

### ISSUE THREAD

**Issue by Maximilian-Roth** [ben-z/free-sidecar#8]
Hi there, I wanted to try out free sidecar on my MacBook Pro 2015 (A1502) and my iPad Pro 10,5" (iPad7,3 A1701 (EMC 3140*)) - so I wondered that the "iPad7,3" is not in the Enable List in the UI. Has this just only fogotten or are there issues with this model? I just tried to enable all the other iPad models in the list but not luck with getting sidecar to work...

Thanks for you help and have a nice sunday.

**Comment by ben-z** [comment]
iPad Pro is supported by Apple. There’s no need to enable it. Just need to enable your MacBook. 

Did you try wired connection?

**Comment by Maximilian-Roth** [comment]
Thank you, that it was - now SideCar is working flawlessly :-)

**Comment by ben-z** [comment]
Awesome to hear!
