### ISSUE TITLE
Mac Book Pro 2013 version bad quality 

### ISSUE THREAD

**Issue by JustinBrg** [ben-z/free-sidecar#80]
Please fill in the template below to speed up the review process:

**Mac model:** Pro Late 2013, 10.15.4
**iPad model:** Pro 2020

**Comments:** I managed to get sidecar working on an older unsupported version -> My Mac Book, and it is wireless connected with my Ipad Pro, but the quality is really really bad, like the Mac Book Desktop I see on my Ipad is really bad and laggy.

Someone any experience with this Problem or an idea?

**Comment by ben-z** [comment]
The only thing I can think of is try wired connection. It's common to see bad quality on older Macs with newer iPads, probably because of the lack of HEVC hardware in older Macs.

**Comment by pherkan** [comment]
Same issue here with MacBook Pro Mid-2014 and iPad Pro 11". Even with wired connection, the screen on the iPad is glitchy (as if it's a TV screen from the 90s).

**Comment by leon0707** [comment]
I'm using mid 2014 macbook pro and upgraded macos from mojave to catalina for sidecar. The screen on ipad pro 2018 is bad.

**Comment by eksch** [comment]
Same here, Sidecar now works but screen is pixelated and glitchy.
MacBook Pro, Early 2013, running 10.15.4 
iPad Pro 12.9", 3rd gen

**Comment by CelestialSayuki** [comment]
My old Macbook Pro Late 2013 has a bad quality as well.

**Comment by CPS2020** [comment]
I can confirm that my Mid-2014 MacBook Pro has this problem as well, both in wired and wireless mode.

Mac model: MacBookPro11,1
iPad model: iPad6,3

Mac version: Catalina 10.15.5 beta 5 (just updated today)
iPad version: 13.5

Cheers,
Claus.

**Comment by errthou** [comment]
Mac model: MacBookPro11,1
iPad model: iPad8,1

Mac version: Catalina 10.15.5 
iPad version: 13.5

maybe it should be in readme, so other users find it out in the very beginning? older macs that isn't support hardware HEVC are incapable of sidecar and system level support disabled due technical reasons, not only marketing? sidecar screen sharing on unsupported mac looks terrible and cannot be fixed

**Comment by ben-z** [comment]
Valid point, I'm having a hard time pinpointing the specific devices that have this issue though. The quality is pretty good on my MPB 13" 2015 with iPad Air 2.
