### ISSUE TITLE
My apps still aren’t opening AFTER I restored the SidecarCore .bak file. Help?!

### ISSUE THREAD

**Issue by forcequitOS** [ben-z/free-sidecar#81]
**MacBook Air 7,1**
**iPad 11,1**

**macOS 10.15.4 (Supplemental Patch)**:
**iPadOS 13.4.5 (Dev Beta 2)**:

So, I had installed it and my apps weren’t working (I had tried troubleshooting steps already and CodeSign showed no issues), so I wanted to revert. I reverted the SidecarCore file as said. But Finder and essentially anything but Terminal (Spotlight doesn’t work and even all the little Menu Bar icons are gone!) crashes on launch AFTER restoring SidecarCore and finally disabling SIP. What do I need to do to fix this?

**Comment by forcequitOS** [comment]
And oddly enough, disabling SIP again allows the Finder to work, but the Menu Bar applets are still broken and most apps still don’t work

**Comment by ben-z** [comment]
Did you modify the nvram boot flag? This is required for 10.15.4+

**Comment by forcequitOS** [comment]
No I didn’t, that explains it...

**Comment by ben-z** [comment]
You shouldn't need to disable SIP and add the boot flag if you have restored the backup though. Chances are you overwrote the backup file with the patched file. You can check by opening the backup file in free-sidecar and see if it's patched.
