### ISSUE TITLE
Task Bar shift

### ISSUE THREAD

**Issue by tequ09** [ben-z/free-sidecar#84]
Please fill in the template below to speed up the review process:

After installing Sidecar, my top task bar has shifted and I am only able to see a couple of options
**Mac model: MackbookPro11,4** 
**iPad model: Ipad 7(10.2)**

**Mac version**:
**iPad version**:

**Comments:**

**Comment by ben-z** [comment]
You are prob on 10.15.4 and didn't add the NVRAM boot flag
