### ISSUE TITLE
missing iPad7,5 (6. Generation WiFi) in devicelist (step 4.)

### ISSUE THREAD

**Issue by sortoftone** [ben-z/free-sidecar#85]
My iPad (6. Generation model number A1893) is not shown as "Enable iPad7,5" in the devicelist at step 4. Had anyone luck with this iPad?
Try to hook it up with MacBookPro11,4 (Retina 15" mid 2015) with Catalina 10.15.4 (19E287).

**Comment by ben-z** [comment]
Is it officially supported?

**Comment by sortoftone** [comment]
Yes, iPad 6.Gen. is offcially supported.
The sidecar controlpanel shows up in system preferences.
Connecting iPad (iOS 13.4.1) with MacBook through USB/Lightning cable does only charge the iPad. iPad is not recognized in sidecar controlpanel.

**Comment by ben-z** [comment]
If it's officially supported then it wouldn't show up in free-sidecar. Try the troubleshooting steps in the README.
