### ISSUE TITLE
Loss of internet connectivity

### ISSUE THREAD

**Issue by cdubzuk** [ben-z/free-sidecar#89]
Please fill in the template below to speed up the review process:

**Mac model:** MacBook Pro 2012
**iPad model:** iPad Pro 2020

**Mac version**: Catalina 10.4(latest version)
**iPad version**: latest version 

**Comments:**
I’ve run through the whole process several times and each time once I get everything installed I lose the clock, the ability to launch apps, and my network connection (although sidecar works).

The real issue occurs however when I try to revert to the backup. I’ve done all of the steps and have managed to get apps running again, but I can’t get my internet connection to turn back on. My USB connection is also painfully slow as it took over 15 hours to copy 1gig (the stick works just fine on other laptops). I’ve tried reinstall the OS from the Mac combo update as described in sidecar patchers FAQ, tried reinstalling the OS from the recovery mode three times, and tried both re-enabling and restoring from backup as per the steps about 8 times to no avail.

I’m getting and IP and MAC address but the network connection and USB connections just won’t function properly. I’d like to avoid a full reformat if I can, but I’m not entirely convinced even that would work at this point. I’m at my wits end so any help would be greatly appreciated!

**Comment by ben-z** [comment]
Did you modify the boot flag during step 8? It’s required for 10.15.4+.

**Comment by ben-z** [comment]
Also did you accidentally overwrote your backup with the patched SidecarCore? You can check this by opening the backup file with free-sidecar.

**Comment by cdubzuk** [comment]
double checked and I haven't overwritten the backup, so that's positive at least.

Gone through and done all of the steps again and this time it seems to have worked (including the internet connection) so seems to have fixed itself somehow.

Seems it just took me asking for help!
