### ISSUE TITLE
Macbookpro 2018 doesn’t revert back

### ISSUE THREAD

**Issue by Efraimbo** [ben-z/free-sidecar#90]
Please fill in the template below to speed up the review process:

**Mac model:** MacBook Pro 2018
**iPad model:**ipad air 2

**Mac version**:10.15.4
**iPad version**:13.3.1

**Comments:**
It didn’t work even though i tried wired connection and enabled all the ipads in the application so I wanted to revert back to the original sidecar but forgot to remove the boot flag so when i enabled the system integrity protection and rebooted only the terminal was working and no other application launched even the finder an i couldn’t access my files so i deleted from the terminal the boot flag and restarted. No difference happened, and i tried resetting the nvram but now i can only use some apps when i disable the system integrity protection.
Please help me!! Several apps are not working like safari and the app store 
Sorry for making this long,

**Comment by ben-z** [comment]
Did you accidentally overwrite the backup file with the patched SidecarCore? You can check this by opening the SidecarCore from the system folder in free-sidecar. Also keep your SIP disabled until apps start working.
