### ISSUE TITLE
Updated to 10.15.4, no longer working, please help

### ISSUE THREAD

**Issue by jay-p144** [ben-z/free-sidecar#91]
Please fill in the template below to speed up the review process:

**Mac model:**MacBookPro 2019
**iPad model:** iPad Air 2

**Mac version**: 10.15.4
**iPad version**:13.4

**Comments:**
I had this working flawlessly before, and then my Mac auto updated to 10.15.4. My Mac would no longer pick up the connection when plugged in. I thought to delete the Sidecar files (free sidecar, SidecarCore) and reinstall everything. However, I did not realize what deleting SidecarCore would do, and now when I get to step 6 I get a message in terminal that says
 “mount_apfs: volume could not be mounted: Operation not permitted 
mount: / failed with 77”

Did I corrupt the SidecarCore file that originally came on the device? I do not have the backups from before anymore.

**Comment by ben-z** [comment]
Your SIP is probably on. That error seems unrelated to the missing SidecarCore file.

**Comment by ben-z** [comment]
Try re-patching it. Make sure to set the boot flags according to the README.
