### ISSUE TITLE
Error(-6709)

### ISSUE THREAD

**Issue by CelestialSayuki** [ben-z/free-sidecar#92]
Please fill in the template below to speed up the review process:

**Mac model:Macbook Air 2020
**iPad model:iPad Air 2(iPad 5,3)

**Mac version**:10.15.4(19E258)
**iPad version**:13.5(17F5065a)

**Comments:**
Both using wire and wireless aren't work, it is Error(-6709). I've signed and added amfi_get_out_of_my_way=0x1, I think I have trobuleshot. Please help!
![截屏2020-05-16 下午6 52 47](https://user-images.githubusercontent.com/50404193/82118034-0a845a00-97a7-11ea-9954-ffe175bd584a.png)

**Comment by ben-z** [comment]
Did you try wired (turn off bluetooth and wifi on the iPad).

**Comment by CelestialSayuki** [comment]
Yes, I have tried wired.

**Comment by ben-z** [comment]
I've never seen error 6709 before. Is it the same error code every time?

A quick Google search gave me a few results. Likely a bug in Sidecar:
https://discussions.apple.com/thread/250713641
https://www.reddit.com/r/ipad/comments/fo5keo/sidecar_issues/

**Comment by CelestialSayuki** [comment]
Yes, It's same every time.

**Comment by CelestialSayuki** [comment]
Well my old MacBook Pro 2014 with iPad Air 2 doesn't error, but bad quality.

**Comment by ben-z** [comment]
The new Macbook Air officially supports Sidecar so you should get better quality once it works. Can you verify that you have logged into the same Apple ID and trusted the device from Finder? Also can you list the troubleshooting steps that you have done and try the ones that you haven't done?

**Comment by CelestialSayuki** [comment]
Yes. I've logged in the same ID and trusted in Finder. I've troubleshot but still not work.

**Comment by CelestialSayuki** [comment]
Well, now it works. After ejecting the WLAN card, it works now.

**Comment by win1010525** [comment]
MacOS version:10.15.4（19E286）

**Comment by CelestialSayuki** [comment]
macOS version:19E258

**Comment by CelestialSayuki** [comment]
When having (-6709) you can try eject wlan card and reinject it.

**Comment by pbxyliang1** [comment]
I turn off the Bluetooth and the wireless card and reopen them. The problem is solved。
