### ISSUE TITLE
iPad11,3 missing from Step 4

### ISSUE THREAD

**Issue by connorhopkins** [ben-z/free-sidecar#93]
iPad11,3 is missing from Step 4 of the instruction app, even though it is listed as one of the supported devices. Without this, and just selecting my mac (MacBookPro12,1), the devices box just shows "No Devices", as displayed in the screenshot here. Thanks for the help! 
<img width="626" alt="Screen Shot 2020-05-16 at 8 42 09 PM" src="https://user-images.githubusercontent.com/41088679/82135273-b7fe6a00-97b5-11ea-89f8-4fae2f0cf2a8.png">

**Comment by ben-z** [comment]
What troubleshooting steps have you tried?

**Comment by ben-z** [comment]
If the iPad is officially supported then it won't need patching and won't show up in free-sidecar.

**Comment by connorhopkins** [comment]
Ah okay thank you for the clarification! Also thank you for your work on the patch! So far I've looked through the issues page since none of the other steps pertained to me. Seems like someone had a similar issue to mine (#85 ), but I didn't see how they were able resolve it. So far it still just says "No devices".

**Comment by ben-z** [comment]
I remember there were a couple of closed issues related to this. The main solutions are
1. Make sure both devices are logged into the same Apple ID
2. Make sure the iPad is trusted from Finder
3. When trying wired mode. Make sure the iPad's Wifi and Bluetooth are off.

**Comment by james-s-w-clark** [comment]
> If the iPad is officially supported then it won't need patching and won't show up in free-sidecar.

Could be handy to note this in the app - was looking for ipad7,5 (2019 iPad)
