### ISSUE TITLE
MacBook Pro 16 completely screwed up after install try

### ISSUE THREAD

**Issue by SteLPC** [ben-z/free-sidecar#94]
Please fill in the template below to speed up the review process:

**Mac model:** MacBook Pro 16,1
**iPad model:** iPad Air 2

**Mac version**: 10.15.4 (Latest)
**iPad version**: latest 

**Comments:**
Hi,
I tried to install free sidecar on latest release of catalina
When I discovered that I needed to keep SIP disabled I wanted not to install anymore and tried to revert backup file.
I might have screwed up something. This led to an unusable Mac, time and date in menu bar won’t show up anymore and everything I tried to open, included terminal, ended in a EXC_CRASH (SIGABRT).
I tried to revert from a time machine backup but the issue was still there.
Tried to reinstall macosx but now it is stuck on user selection page, when I type the password for my user it keeps loading and doesn’t start.
The time machine was my only backup, now I’m frightened to have all my files lost. Hope there is something I can do.
Thankyou

**Comment by SteLPC** [comment]
Update: I restored another time from time machine. The sidecar backup file is gone unfortunately, but terminal works, and it looks it is the only thing working.
Furthermore, I cannot either disable system integrity protection from recovery, it let me give the command but the restart button (nor shut down) does not work, and I’m forced to shut down with touchid button. At restart SIP is enabled (I checked with csrutil status).
Please help, I’m a surgeon and there are files I need for tomorrow!
Thank you for any help.

**Comment by ben-z** [comment]
Are you saying that you can't reinstall your mac and can't disable SIP? That's pretty weird.

**Comment by ben-z** [comment]
Since you don't have the backup file anymore. Reinstalling the mac may be the best way to go. Try to figure out why you can't reinstall using the recovery partition.

Alternatively you can try to find a SidecarCore file online but I wouldn't recommend putting untrusted frameworks into your system folder.

**Comment by SteLPC** [comment]
Thankyou for your response.
I restored from time machine, and finder keeps crashing (even in safe mode). Using cmd + R, terminal won’t allow reboot therefore no command can be applied and I couldn’t unable SIP.
I then performed system reinstall from cmd+R and I was finally able to enter the system without the continuous crashes but I lost admin privileges.
For now I will manually copy my files onto an hd and perform a clean install of catalina.
May I ask two questions:
- Which do you think is the best/easier way to perform a clean install to get rid of all errors?
- After the clean install can I use the time machine backup again? Do you think it could be in any way corrupted?

Many thanks for your time, really appreciate.

**Comment by ben-z** [comment]
What do you mean you lost admin privileges? The reinstall shouldn't affect any of your user accounts unless you had some special setup that modified system files.

I'm not too familiar with time machine but it should restore all of your user files from my experience.

Also why do you need a clean install? Reinstalling from recovery mode should restore all of the system files.

**Comment by SteLPC** [comment]
My account (the only one in the Mac) is now set as “standard” after time machine reinstall + recovery reinstall of os.
There simply isn’t an admin account anymore (therefore no system pref modifications allowed or app install, etc)

The reinstall from recovery I think is just an update on top of the system, as my problems are still there. Looks like there are some security certificates not working properly.

I thought to have done everything right but I must have messed up something!

**Comment by ben-z** [comment]
Uhhh I'm not too familiar with the reinstallation process. This is out of the scope of this project so I think it's the best to look elsewhere on reinstalling.

**Comment by SteLPC** [comment]
Thank you for your time, I will perform a clean install and hope for the best!

**Comment by telnetdoogie** [comment]
for others having this issue (menu bar broken, cannot open apps)

- Go back and disable SIP again (`csrutil disable` in recovery mode) and reboot back to MacOS
- open Terminal (may have to browse to /Applications/Utilities/ and double-click Terminal)
- Mount system volume as read-write `sudo mount -uw /`
- copy the backup back into System `sudo cp ~/Downloads/SidecarCore.bak /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore`

Reboot.

Do NOT re-sign the original application again. Once you reboot, and everything looks normal again, you should be able to go back into Recovery Mode and `csrutil enable` 

- Back where you started.

This appears to be an issue with Catalina 10.15.4 and the Readme.MD has been updated with a workaround

**Comment by arnoldjames98** [comment]
Does the `csrutil enable` command need to be run after completing these steps to go back? If I don't run this command what is the effect?

**Comment by ben-z** [comment]
@arnoldjames98 nope. If you don't run it SIP stays disabled. Other than that this has no effect.

**Comment by volkangurol** [comment]
@telnetdoogie solution works for me.

**Comment by BRadHoc** [comment]
On 15.5.5 on macbook pro 16, same issue with status bar and applications like chrome crash when you try and right click on it or use any keyboard shortcuts. I added the bootflag:

> sudo nvram boot-args="amfi_get_out_of_my_way=0x1"

and left SIP disabled however still same issue. Used @telnetdoogie's solution to revert and:

> sudo nvram -d boot-args

to remove the bootflag and everything is working again, maybe .5 broke it?

**Comment by BRadHoc** [comment]
Does the bootflag need to be added before the file is patched etc? I'm wondering if I did something in the wrong order?

**Comment by ben-z** [comment]
The order shouldn't matter, as long as they are both completed before reboot.

I just tested free-sidecar on MBP 2015 13" running Catalina 10.15.5 and it works fine. Wireless also started working after this update LOL (didn't work before).

**Comment by aiyouBug** [comment]
昨天在macpro16的电脑上安装该补丁，导致系统崩溃，我通过创建映象的方式吧桌面以及重要文件备份后再不抹除硬盘的情况重新安装系统，重启过后系统恢复正常。
Trying this patch yesterday caused the system to crash
Here's how I solved it
command+r
1. Backup files by creating an image
2. Reinstall the system
