### ISSUE TITLE
*replacing existing signature* - when is it done after step 8?

### ISSUE THREAD

**Issue by xx-arch** [ben-z/free-sidecar#95]
**Mac model: MacBook Pro (Retina, 15', Mid 2015)
**iPad model: Ipad 7

**Comments:**
I don't know when the code will run, I also don't understand #59 what I should with this weird 'get_out_of_my_way' type thing.

this is the last line I get:

MBP:~ nicolas$ sudo codesign -f -s - /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore 
/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: replacing existing signature
MBP:~ nicolas$

**Comment by ben-z** [comment]
What's your question?

**Comment by xx-arch** [comment]
in #59 you suggest: 1. 

> Before restarting, add amfi_get_out_of_my_way=0x1 to your NVRAM boot flags. i.e. run sudo nvram boot-args="amfi_get_out_of_my_way=0x1". You should not see any error messages.

Where in the command 
`sudo codesign -f -s - /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore` do should I add that? and is there somewhere to put my 'error' replacing existing signature? 
What do I do next?

Thank you!

**Comment by ben-z** [comment]
`/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: replacing existing signature` is a normal message indicating that SidecarCore was already signed.

After the code signing step you should run `sudo nvram boot-args="amfi_get_out_of_my_way=0x1"` to add an NVRAM boot flag so that macOS accepts self-signed binaries in system frameworks.

**Comment by xx-arch** [comment]
yes okay, that worked too. And now nothing else in Terminal right? 
But it still won't show the iPad as a monitor?

Thank you for your kind help.

**Comment by ben-z** [comment]
After restarting the computer you should see the sidecar preference pane and an icon in the status bar:
![image](https://user-images.githubusercontent.com/5977478/82239482-a9b36980-98ed-11ea-8243-203b1765d184.png)
![image](https://user-images.githubusercontent.com/5977478/82239489-addf8700-98ed-11ea-9ae3-382916b6347f.png)
In there you should find your iPad. If you don't see your iPad in the list. Try the troubleshooting steps in the README.

**Comment by xx-arch** [comment]
Unfortunately I don't see that. I used to the the monitor Apple TV sign, but that has disappeared now as well. 
After logging in and out and deleting the preference file nothing changed.
Restarted like 15 times now. Not working.

Also I don't see the iPad in finder, only in iTunes - there I clicked 'trust'.

**Comment by ben-z** [comment]
Check to see if the SidecarCore in the system folder is patched by opening it with free-sidecar. Make sure the correct mac model is selected.

**Comment by xx-arch** [comment]
Ah! Actually it was not selected apparently, because I thought I needed to click on the green button - the description wasn't 100% clear there. Now every device is enabled - like the default downloaded software. 

Now I can see the iPad and I get another warning: Can't screen share due to timeout! 
So now I did the same trouble shooting again but can't get it working.
