### ISSUE TITLE
Tried to download and now nothing works

### ISSUE THREAD

**Issue by BATTUKEGROEG** [ben-z/free-sidecar#96]
So I attempted to use this program and I thought I did it right but then after it was done I still couldn’t view my I pad (but I was able to get to side car so that was good) but then I realized that my google chrome wasn’t working. I thought nothing of it and tried to do the whole the again AND THEN THERE WERE SEVRAL PROBLEMS. Other than mail news podcasts text edit and terminal (and a couple of downloaded applications like Minecraft steam and Spotify ) nothing would open without instantly closing including folder and system preferences  (all the data is still there but for some reason it won’t open) so then I dicided that mabey it was cause I didn’t turn on sip like you said not to if your on 1.14.5 and I tried that but still nothing changed

Please help
It’s an Mac book air (don’t remover the exact one)
4,4

15.4
11.4.1

**Comments:**

**Comment by BATTUKEGROEG** [comment]
Edit: read troubleshooting and that got most of the things on my Mac back except for safari google chrome and applestore (as well as the security in the system preferences) I still can’t find my I pad though

**Comment by ben-z** [comment]
Make sure to keep SIP off and add the NVRAM boot flag.

**Comment by BATTUKEGROEG** [comment]
Okay so what’s the NVRAM boot flag. I don’t know I I just missed that step
but I don’t remember what that is or how to access it

**Comment by ben-z** [comment]
It's under step 8 in the README

**Comment by BATTUKEGROEG** [comment]
Thank you very much
I found it earlier and now my Mac is back up and running again thank you
very much
-- 
hi I don’t know what to put here
